/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DCIReportModule"
 * 	found in "dci_test.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_DCIReport_H_
#define	_DCIReport_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MetaDataHeader.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DCIReport */
typedef struct DCIReport {
	MetaDataHeader_t	 metadataheader;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DCIReport_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DCIReport;

#ifdef __cplusplus
}
#endif

#endif	/* _DCIReport_H_ */
#include <asn_internal.h>
