/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DCIReportModule"
 * 	found in "dci_test.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_DCIUL_H_
#define	_DCIUL_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include "CELLINDEX.h"
#include "SRSQUEST.h"
#include "ModulationType.h"
#include "HOPPINGFLAG.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DCIUL */
typedef struct DCIUL {
	BIT_STRING_t	 kofdci0;
	BIT_STRING_t	 ulinedxdai;
	CELLINDEX_t	 cellIndex;
	BIT_STRING_t	 tpc;
	BIT_STRING_t	 harqid;
	BIT_STRING_t	 ndi;
	BIT_STRING_t	 rntitype;
	BIT_STRING_t	 tbsindex;
	BIT_STRING_t	 mcsindex;
	BIT_STRING_t	 redundancyversionindex;
	BIT_STRING_t	 skip5;
	BIT_STRING_t	 resourceallocationtype;
	SRSQUEST_t	 srsquest;
	BIT_STRING_t	 cqirequest;
	ModulationType_t	 modulationtype;
	BIT_STRING_t	 numberofresourceblocks;
	BIT_STRING_t	 startofresourceblock;
	BIT_STRING_t	 rbgsize;
	HOPPINGFLAG_t	 hoppingflag;
	BIT_STRING_t	 searchspace;
	BIT_STRING_t	 skip6;
	BIT_STRING_t	 cyclicshiftdmrs;
	BIT_STRING_t	 skip7;
	BIT_STRING_t	 rivvalue;
	BIT_STRING_t	 rivwidth;
	BIT_STRING_t	 numberofresourceblocks2;
	BIT_STRING_t	 startofresourceblock2;
	BIT_STRING_t	 skip8;
	BIT_STRING_t	 skip9;
	BIT_STRING_t	 aggregationlevel;
	BIT_STRING_t	 skip10;
	OCTET_STRING_t	 skip11;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DCIUL_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DCIUL;

#ifdef __cplusplus
}
#endif

#endif	/* _DCIUL_H_ */
#include <asn_internal.h>
