/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DCIReportModule"
 * 	found in "dci_test.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_DlGrantFormatType_H_
#define	_DlGrantFormatType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DlGrantFormatType {
	DlGrantFormatType_type1a	= 0,
	DlGrantFormatType_type2	= 1,
	DlGrantFormatType_unknown	= 2,
	DlGrantFormatType_unknown1	= 3
} e_DlGrantFormatType;

/* DlGrantFormatType */
typedef long	 DlGrantFormatType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DlGrantFormatType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DlGrantFormatType;
extern const asn_INTEGER_specifics_t asn_SPC_DlGrantFormatType_specs_1;
asn_struct_free_f DlGrantFormatType_free;
asn_struct_print_f DlGrantFormatType_print;
asn_constr_check_f DlGrantFormatType_constraint;
ber_type_decoder_f DlGrantFormatType_decode_ber;
der_type_encoder_f DlGrantFormatType_encode_der;
xer_type_decoder_f DlGrantFormatType_decode_xer;
xer_type_encoder_f DlGrantFormatType_encode_xer;
oer_type_decoder_f DlGrantFormatType_decode_oer;
oer_type_encoder_f DlGrantFormatType_encode_oer;
per_type_decoder_f DlGrantFormatType_decode_uper;
per_type_encoder_f DlGrantFormatType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DlGrantFormatType_H_ */
#include <asn_internal.h>
