/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DCIReportModule"
 * 	found in "dci_test.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "ModulationType.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_ModulationType_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_ModulationType_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_ModulationType_value2enum_1[] = {
	{ 0,	8,	"unknown0" },
	{ 1,	8,	"unknown1" },
	{ 2,	6,	"i16qam" },
	{ 3,	6,	"i64qam" },
	{ 4,	8,	"unknown4" },
	{ 5,	8,	"unknown5" },
	{ 6,	8,	"unknown6" },
	{ 7,	8,	"unknown7" }
};
static const unsigned int asn_MAP_ModulationType_enum2value_1[] = {
	2,	/* i16qam(2) */
	3,	/* i64qam(3) */
	0,	/* unknown0(0) */
	1,	/* unknown1(1) */
	4,	/* unknown4(4) */
	5,	/* unknown5(5) */
	6,	/* unknown6(6) */
	7	/* unknown7(7) */
};
const asn_INTEGER_specifics_t asn_SPC_ModulationType_specs_1 = {
	asn_MAP_ModulationType_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_ModulationType_enum2value_1,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ModulationType_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ModulationType = {
	"ModulationType",
	"ModulationType",
	&asn_OP_NativeEnumerated,
	asn_DEF_ModulationType_tags_1,
	sizeof(asn_DEF_ModulationType_tags_1)
		/sizeof(asn_DEF_ModulationType_tags_1[0]), /* 1 */
	asn_DEF_ModulationType_tags_1,	/* Same as above */
	sizeof(asn_DEF_ModulationType_tags_1)
		/sizeof(asn_DEF_ModulationType_tags_1[0]), /* 1 */
	{ &asn_OER_type_ModulationType_constr_1, &asn_PER_type_ModulationType_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ModulationType_specs_1	/* Additional specs */
};

