/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DCIReportModule"
 * 	found in "dci_test.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_TpcDciRntiType_H_
#define	_TpcDciRntiType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TpcDciRntiType {
	TpcDciRntiType_crnti	= 0,
	TpcDciRntiType_unknown	= 1
} e_TpcDciRntiType;

/* TpcDciRntiType */
typedef long	 TpcDciRntiType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TpcDciRntiType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TpcDciRntiType;
extern const asn_INTEGER_specifics_t asn_SPC_TpcDciRntiType_specs_1;
asn_struct_free_f TpcDciRntiType_free;
asn_struct_print_f TpcDciRntiType_print;
asn_constr_check_f TpcDciRntiType_constraint;
ber_type_decoder_f TpcDciRntiType_decode_ber;
der_type_encoder_f TpcDciRntiType_encode_der;
xer_type_decoder_f TpcDciRntiType_decode_xer;
xer_type_encoder_f TpcDciRntiType_encode_xer;
oer_type_decoder_f TpcDciRntiType_decode_oer;
oer_type_encoder_f TpcDciRntiType_encode_oer;
per_type_decoder_f TpcDciRntiType_decode_uper;
per_type_encoder_f TpcDciRntiType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TpcDciRntiType_H_ */
#include <asn_internal.h>
