/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RLC-DL-AM-Control-PDU"
 * 	found in "LTE_RLC_DL_AM_Control_PDU.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "AM-PDU.h"

asn_TYPE_member_t asn_MBR_AM_PDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AM_PDU, pdu_based_on_dc_union),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Control_PDU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pdu-based-on-dc-union"
		},
};
static const ber_tlv_tag_t asn_DEF_AM_PDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AM_PDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* pdu-based-on-dc-union */
};
asn_SEQUENCE_specifics_t asn_SPC_AM_PDU_specs_1 = {
	sizeof(struct AM_PDU),
	offsetof(struct AM_PDU, _asn_ctx),
	asn_MAP_AM_PDU_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AM_PDU = {
	"AM-PDU",
	"AM-PDU",
	&asn_OP_SEQUENCE,
	asn_DEF_AM_PDU_tags_1,
	sizeof(asn_DEF_AM_PDU_tags_1)
		/sizeof(asn_DEF_AM_PDU_tags_1[0]), /* 1 */
	asn_DEF_AM_PDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_AM_PDU_tags_1)
		/sizeof(asn_DEF_AM_PDU_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AM_PDU_1,
	1,	/* Elements count */
	&asn_SPC_AM_PDU_specs_1	/* Additional specs */
};

