/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RLC-DL-AM-Control-PDU"
 * 	found in "LTE_RLC_DL_AM_Control_PDU.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_AM_PDU_H_
#define	_AM_PDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Control-PDU.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AM-PDU */
typedef struct AM_PDU {
	Control_PDU_t	 pdu_based_on_dc_union;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AM_PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AM_PDU;
extern asn_SEQUENCE_specifics_t asn_SPC_AM_PDU_specs_1;
extern asn_TYPE_member_t asn_MBR_AM_PDU_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _AM_PDU_H_ */
#include <asn_internal.h>
