/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-AdvRx-IC-Cell-List"
 * 	found in "LTE_ML1_AdvRx_IC_Cell_List.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Carrier_index_H_
#define	_Carrier_index_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Carrier_index {
	Carrier_index_pcc	= 0,
	Carrier_index_scc1	= 1,
	Carrier_index_scc2	= 2
} e_Carrier_index;

/* Carrier-index */
typedef long	 Carrier_index_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Carrier_index_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Carrier_index;
extern const asn_INTEGER_specifics_t asn_SPC_Carrier_index_specs_1;
asn_struct_free_f Carrier_index_free;
asn_struct_print_f Carrier_index_print;
asn_constr_check_f Carrier_index_constraint;
ber_type_decoder_f Carrier_index_decode_ber;
der_type_encoder_f Carrier_index_encode_der;
xer_type_decoder_f Carrier_index_decode_xer;
xer_type_encoder_f Carrier_index_encode_xer;
oer_type_decoder_f Carrier_index_decode_oer;
oer_type_encoder_f Carrier_index_encode_oer;
per_type_decoder_f Carrier_index_decode_uper;
per_type_encoder_f Carrier_index_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Carrier_index_H_ */
#include <asn_internal.h>
