/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-AdvRx-IC-Cell-List"
 * 	found in "LTE_ML1_AdvRx_IC_Cell_List.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Cell_Type_H_
#define	_Cell_Type_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Cell_Type {
	Cell_Type_unknown0	= 0,
	Cell_Type_cELL_UNMEASURED	= 1,
	Cell_Type_cELL_ASYNC	= 2,
	Cell_Type_unkownn3	= 3,
	Cell_Type_unknown4	= 4,
	Cell_Type_cELL_NOT_IN_IC_LIST	= 5
} e_Cell_Type;

/* Cell-Type */
typedef long	 Cell_Type_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Cell_Type_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Cell_Type;
extern const asn_INTEGER_specifics_t asn_SPC_Cell_Type_specs_1;
asn_struct_free_f Cell_Type_free;
asn_struct_print_f Cell_Type_print;
asn_constr_check_f Cell_Type_constraint;
ber_type_decoder_f Cell_Type_decode_ber;
der_type_encoder_f Cell_Type_encode_der;
xer_type_decoder_f Cell_Type_decode_xer;
xer_type_encoder_f Cell_Type_encode_xer;
oer_type_decoder_f Cell_Type_decode_oer;
oer_type_encoder_f Cell_Type_encode_oer;
per_type_decoder_f Cell_Type_decode_uper;
per_type_encoder_f Cell_Type_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Cell_Type_H_ */
#include <asn_internal.h>
