/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-AdvRx-IC-Cell-List"
 * 	found in "LTE_ML1_AdvRx_IC_Cell_List.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Cell_type_H_
#define	_Cell_type_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Cell_type {
	Cell_type_unknown0	= 0,
	Cell_type_cELL_SERVING	= 1
} e_Cell_type;

/* Cell-type */
typedef long	 Cell_type_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Cell_type_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Cell_type;
extern const asn_INTEGER_specifics_t asn_SPC_Cell_type_specs_1;
asn_struct_free_f Cell_type_free;
asn_struct_print_f Cell_type_print;
asn_constr_check_f Cell_type_constraint;
ber_type_decoder_f Cell_type_decode_ber;
der_type_encoder_f Cell_type_encode_der;
xer_type_decoder_f Cell_type_decode_xer;
xer_type_encoder_f Cell_type_encode_xer;
oer_type_decoder_f Cell_type_decode_oer;
oer_type_encoder_f Cell_type_encode_oer;
per_type_decoder_f Cell_type_decode_uper;
per_type_encoder_f Cell_type_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Cell_type_H_ */
#include <asn_internal.h>
