/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RLC-DL-AM-Control-PDU"
 * 	found in "LTE_RLC_DL_AM_Control_PDU.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Cpt_H_
#define	_Cpt_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Cpt {
	Cpt_status	= 0,
	Cpt_unknown1	= 1,
	Cpt_unknown2	= 2,
	Cpt_unknown3	= 3,
	Cpt_unknown4	= 4,
	Cpt_unknown5	= 5,
	Cpt_unknown6	= 6,
	Cpt_unknown7	= 7
} e_Cpt;

/* Cpt */
typedef long	 Cpt_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Cpt_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Cpt;
extern const asn_INTEGER_specifics_t asn_SPC_Cpt_specs_1;
asn_struct_free_f Cpt_free;
asn_struct_print_f Cpt_print;
asn_constr_check_f Cpt_constraint;
ber_type_decoder_f Cpt_decode_ber;
der_type_encoder_f Cpt_encode_der;
xer_type_decoder_f Cpt_decode_xer;
xer_type_encoder_f Cpt_encode_xer;
oer_type_decoder_f Cpt_decode_oer;
oer_type_encoder_f Cpt_encode_oer;
per_type_decoder_f Cpt_decode_uper;
per_type_encoder_f Cpt_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Cpt_H_ */
#include <asn_internal.h>
