/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-UE-Identification-Message-MSG3-Report"
 * 	found in "LTE_UE_Identification_Message_MSG3_Report.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Cqi_H_
#define	_Cqi_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Cqi {
	Cqi_disabled	= 0,
	Cqi_abled	= 1
} e_Cqi;

/* Cqi */
typedef long	 Cqi_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Cqi_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Cqi;
extern const asn_INTEGER_specifics_t asn_SPC_Cqi_specs_1;
asn_struct_free_f Cqi_free;
asn_struct_print_f Cqi_print;
asn_constr_check_f Cqi_constraint;
ber_type_decoder_f Cqi_decode_ber;
der_type_encoder_f Cqi_encode_der;
xer_type_decoder_f Cqi_decode_xer;
xer_type_encoder_f Cqi_encode_xer;
oer_type_decoder_f Cqi_decode_oer;
oer_type_encoder_f Cqi_encode_oer;
per_type_decoder_f Cqi_decode_uper;
per_type_encoder_f Cqi_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Cqi_H_ */
#include <asn_internal.h>
