/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DCIReportModule"
 * 	found in "LTE_ML1_DCI_Information_Report.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_DCIReportModule_ModulationType_H_
#define	_DCIReportModule_ModulationType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DCIReportModule_ModulationType {
	DCIReportModule_ModulationType_unknown0	= 0,
	DCIReportModule_ModulationType_qpsk	= 1,
	DCIReportModule_ModulationType_i16qam	= 2,
	DCIReportModule_ModulationType_i64qam	= 3,
	DCIReportModule_ModulationType_i256qam	= 4,
	DCIReportModule_ModulationType_unknown5	= 5,
	DCIReportModule_ModulationType_unknown6	= 6,
	DCIReportModule_ModulationType_unknown7	= 7
} e_DCIReportModule_ModulationType;

/* ModulationType */
typedef long	 DCIReportModule_ModulationType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DCIReportModule_ModulationType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DCIReportModule_ModulationType;
extern const asn_INTEGER_specifics_t asn_SPC_DCIReportModule_ModulationType_specs_1;
asn_struct_free_f DCIReportModule_ModulationType_free;
asn_struct_print_f DCIReportModule_ModulationType_print;
asn_constr_check_f DCIReportModule_ModulationType_constraint;
ber_type_decoder_f DCIReportModule_ModulationType_decode_ber;
der_type_encoder_f DCIReportModule_ModulationType_encode_der;
xer_type_decoder_f DCIReportModule_ModulationType_decode_xer;
xer_type_encoder_f DCIReportModule_ModulationType_encode_xer;
oer_type_decoder_f DCIReportModule_ModulationType_decode_oer;
oer_type_encoder_f DCIReportModule_ModulationType_encode_oer;
per_type_decoder_f DCIReportModule_ModulationType_decode_uper;
per_type_encoder_f DCIReportModule_ModulationType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DCIReportModule_ModulationType_H_ */
#include <asn_internal.h>
