/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-S-Criteria-Check-Procedure"
 * 	found in "LTE_ML1_S_Criteria_Check_Procedure.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Display_Avg_H_
#define	_Display_Avg_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Display_Avg {
	Display_Avg_false	= 0,
	Display_Avg_true	= 1
} e_Display_Avg;

/* Display-Avg */
typedef long	 Display_Avg_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Display_Avg_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Display_Avg;
extern const asn_INTEGER_specifics_t asn_SPC_Display_Avg_specs_1;
asn_struct_free_f Display_Avg_free;
asn_struct_print_f Display_Avg_print;
asn_constr_check_f Display_Avg_constraint;
ber_type_decoder_f Display_Avg_decode_ber;
der_type_encoder_f Display_Avg_encode_der;
xer_type_decoder_f Display_Avg_decode_xer;
xer_type_encoder_f Display_Avg_encode_xer;
oer_type_decoder_f Display_Avg_decode_oer;
oer_type_encoder_f Display_Avg_encode_oer;
per_type_decoder_f Display_Avg_decode_uper;
per_type_encoder_f Display_Avg_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Display_Avg_H_ */
#include <asn_internal.h>
