/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-RRC-Supported-CA-Combos"
 * 	found in "LTE_RRC_Supported_CA_Combos.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "Dl-Bw-Class.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_Dl_Bw_Class_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_Dl_Bw_Class_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_Dl_Bw_Class_value2enum_1[] = {
	{ 0,	16,	"cA-BW-CLASS-NONE" },
	{ 1,	13,	"cA-BW-CLASS-A" },
	{ 2,	13,	"cA-BW-CLASS-B" },
	{ 3,	13,	"cA-BW-CLASS-C" },
	{ 4,	13,	"cA-BW-CLASS-D" },
	{ 5,	13,	"cA-BW-CLASS-E" },
	{ 6,	13,	"cA-BW-CLASS-F" },
	{ 7,	13,	"cA-BW-CLASS-G" }
};
static const unsigned int asn_MAP_Dl_Bw_Class_enum2value_1[] = {
	1,	/* cA-BW-CLASS-A(1) */
	2,	/* cA-BW-CLASS-B(2) */
	3,	/* cA-BW-CLASS-C(3) */
	4,	/* cA-BW-CLASS-D(4) */
	5,	/* cA-BW-CLASS-E(5) */
	6,	/* cA-BW-CLASS-F(6) */
	7,	/* cA-BW-CLASS-G(7) */
	0	/* cA-BW-CLASS-NONE(0) */
};
const asn_INTEGER_specifics_t asn_SPC_Dl_Bw_Class_specs_1 = {
	asn_MAP_Dl_Bw_Class_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_Dl_Bw_Class_enum2value_1,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_Dl_Bw_Class_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Dl_Bw_Class = {
	"Dl-Bw-Class",
	"Dl-Bw-Class",
	&asn_OP_NativeEnumerated,
	asn_DEF_Dl_Bw_Class_tags_1,
	sizeof(asn_DEF_Dl_Bw_Class_tags_1)
		/sizeof(asn_DEF_Dl_Bw_Class_tags_1[0]), /* 1 */
	asn_DEF_Dl_Bw_Class_tags_1,	/* Same as above */
	sizeof(asn_DEF_Dl_Bw_Class_tags_1)
		/sizeof(asn_DEF_Dl_Bw_Class_tags_1[0]), /* 1 */
	{ &asn_OER_type_Dl_Bw_Class_constr_1, &asn_PER_type_Dl_Bw_Class_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_Dl_Bw_Class_specs_1	/* Additional specs */
};

