/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-RRC-Supported-CA-Combos"
 * 	found in "LTE_RRC_Supported_CA_Combos.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Dl_Max_Antennas_Index_H_
#define	_Dl_Max_Antennas_Index_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Dl_Max_Antennas_Index {
	Dl_Max_Antennas_Index_cLASS_INVALID_INDEX	= 0,
	Dl_Max_Antennas_Index_cLASS_A_1_ANT	= 1,
	Dl_Max_Antennas_Index_cLASS_A_2_ANT	= 2,
	Dl_Max_Antennas_Index_cLASS_A_4_ANT	= 3,
	Dl_Max_Antennas_Index_cLASS_BC_1_1_ANT	= 4,
	Dl_Max_Antennas_Index_unknown5	= 5,
	Dl_Max_Antennas_Index_cLASS_BC_2_2_ANT	= 6,
	Dl_Max_Antennas_Index_unknown7	= 7,
	Dl_Max_Antennas_Index_cLASS_BC_4_4_ANT	= 8,
	Dl_Max_Antennas_Index_unknown9	= 9,
	Dl_Max_Antennas_Index_unknown10	= 10,
	Dl_Max_Antennas_Index_unknown11	= 11,
	Dl_Max_Antennas_Index_cLASS_D_2_2_2_ANT	= 12,
	Dl_Max_Antennas_Index_unknown13	= 13,
	Dl_Max_Antennas_Index_unknown14	= 14,
	Dl_Max_Antennas_Index_cLASS_D_4_4_4_ANT	= 15,
	Dl_Max_Antennas_Index_unknown16	= 16,
	Dl_Max_Antennas_Index_unknown17	= 17,
	Dl_Max_Antennas_Index_unknown18	= 18,
	Dl_Max_Antennas_Index_unknown19	= 19,
	Dl_Max_Antennas_Index_cLASS_E_2_2_2_ANT	= 20,
	Dl_Max_Antennas_Index_unknown21	= 21,
	Dl_Max_Antennas_Index_unknown22	= 22,
	Dl_Max_Antennas_Index_unknown23	= 23,
	Dl_Max_Antennas_Index_cLASS_E_4_4_4_ANT	= 24,
	Dl_Max_Antennas_Index_unknown25	= 25,
	Dl_Max_Antennas_Index_unknown26	= 26,
	Dl_Max_Antennas_Index_unknown27	= 27,
	Dl_Max_Antennas_Index_unknown28	= 28,
	Dl_Max_Antennas_Index_unknown29	= 29,
	Dl_Max_Antennas_Index_unknown30	= 30,
	Dl_Max_Antennas_Index_unknown31	= 31,
	Dl_Max_Antennas_Index_unknown32	= 32,
	Dl_Max_Antennas_Index_unknown33	= 33,
	Dl_Max_Antennas_Index_unknown34	= 34,
	Dl_Max_Antennas_Index_cLASS_F_4_4_4_ANT	= 35
} e_Dl_Max_Antennas_Index;

/* Dl-Max-Antennas-Index */
typedef long	 Dl_Max_Antennas_Index_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Dl_Max_Antennas_Index_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Dl_Max_Antennas_Index;
extern const asn_INTEGER_specifics_t asn_SPC_Dl_Max_Antennas_Index_specs_1;
asn_struct_free_f Dl_Max_Antennas_Index_free;
asn_struct_print_f Dl_Max_Antennas_Index_print;
asn_constr_check_f Dl_Max_Antennas_Index_constraint;
ber_type_decoder_f Dl_Max_Antennas_Index_decode_ber;
der_type_encoder_f Dl_Max_Antennas_Index_encode_der;
xer_type_decoder_f Dl_Max_Antennas_Index_decode_xer;
xer_type_encoder_f Dl_Max_Antennas_Index_encode_xer;
oer_type_decoder_f Dl_Max_Antennas_Index_decode_oer;
oer_type_encoder_f Dl_Max_Antennas_Index_encode_oer;
per_type_decoder_f Dl_Max_Antennas_Index_decode_uper;
per_type_encoder_f Dl_Max_Antennas_Index_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Dl_Max_Antennas_Index_H_ */
#include <asn_internal.h>
