/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-GM-TX-Report"
 * 	found in "LTE_ML1_GM_TX_Report.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Duplex_mode_H_
#define	_Duplex_mode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Duplex_mode {
	Duplex_mode_fdd	= 0,
	Duplex_mode_tdd	= 1,
	Duplex_mode_unknown2	= 2
} e_Duplex_mode;

/* Duplex-mode */
typedef long	 Duplex_mode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Duplex_mode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Duplex_mode;
extern const asn_INTEGER_specifics_t asn_SPC_Duplex_mode_specs_1;
asn_struct_free_f Duplex_mode_free;
asn_struct_print_f Duplex_mode_print;
asn_constr_check_f Duplex_mode_constraint;
ber_type_decoder_f Duplex_mode_decode_ber;
der_type_encoder_f Duplex_mode_encode_der;
xer_type_decoder_f Duplex_mode_decode_xer;
xer_type_encoder_f Duplex_mode_encode_xer;
oer_type_decoder_f Duplex_mode_decode_oer;
oer_type_encoder_f Duplex_mode_encode_oer;
per_type_decoder_f Duplex_mode_decode_uper;
per_type_encoder_f Duplex_mode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Duplex_mode_H_ */
#include <asn_internal.h>
