/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-CA-Metrics-Log-Packet"
 * 	found in "LTE_ML1_CA_Metrics_Log_Packet.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "Event.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_Event_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_Event_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  8 }	/* (0..8) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_Event_value2enum_1[] = {
	{ 0,	10,	"sCC-CONFIG" },
	{ 1,	8,	"unknown1" },
	{ 2,	12,	"sCC-ACTIVATE" },
	{ 3,	14,	"sCC-DEACTIVATE" },
	{ 4,	17,	"sCC-VRLF-ACTIVATE" },
	{ 5,	8,	"unknown5" },
	{ 6,	18,	"cONNECTION-RELEASE" },
	{ 7,	8,	"unknown7" },
	{ 8,	8,	"unknown8" }
};
static const unsigned int asn_MAP_Event_enum2value_1[] = {
	6,	/* cONNECTION-RELEASE(6) */
	2,	/* sCC-ACTIVATE(2) */
	0,	/* sCC-CONFIG(0) */
	3,	/* sCC-DEACTIVATE(3) */
	4,	/* sCC-VRLF-ACTIVATE(4) */
	1,	/* unknown1(1) */
	5,	/* unknown5(5) */
	7,	/* unknown7(7) */
	8	/* unknown8(8) */
};
const asn_INTEGER_specifics_t asn_SPC_Event_specs_1 = {
	asn_MAP_Event_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_Event_enum2value_1,	/* N => "tag"; sorted by N */
	9,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_Event_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Event = {
	"Event",
	"Event",
	&asn_OP_NativeEnumerated,
	asn_DEF_Event_tags_1,
	sizeof(asn_DEF_Event_tags_1)
		/sizeof(asn_DEF_Event_tags_1[0]), /* 1 */
	asn_DEF_Event_tags_1,	/* Same as above */
	sizeof(asn_DEF_Event_tags_1)
		/sizeof(asn_DEF_Event_tags_1[0]), /* 1 */
	{ &asn_OER_type_Event_constr_1, &asn_PER_type_Event_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_Event_specs_1	/* Additional specs */
};

