/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-CA-Metrics-Log-Packet"
 * 	found in "LTE_ML1_CA_Metrics_Log_Packet.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Event_H_
#define	_Event_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Event {
	Event_sCC_CONFIG	= 0,
	Event_unknown1	= 1,
	Event_sCC_ACTIVATE	= 2,
	Event_sCC_DEACTIVATE	= 3,
	Event_sCC_VRLF_ACTIVATE	= 4,
	Event_unknown5	= 5,
	Event_cONNECTION_RELEASE	= 6,
	Event_unknown7	= 7,
	Event_unknown8	= 8
} e_Event;

/* Event */
typedef long	 Event_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Event_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Event;
extern const asn_INTEGER_specifics_t asn_SPC_Event_specs_1;
asn_struct_free_f Event_free;
asn_struct_print_f Event_print;
asn_constr_check_f Event_constraint;
ber_type_decoder_f Event_decode_ber;
der_type_encoder_f Event_encode_der;
xer_type_decoder_f Event_decode_xer;
xer_type_encoder_f Event_encode_xer;
oer_type_decoder_f Event_decode_oer;
oer_type_encoder_f Event_encode_oer;
per_type_decoder_f Event_decode_uper;
per_type_encoder_f Event_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Event_H_ */
#include <asn_internal.h>
