/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-GM-TX-Report"
 * 	found in "LTE_ML1_GM_TX_Report.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Freq_hopping_flag_H_
#define	_Freq_hopping_flag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Freq_hopping_flag {
	Freq_hopping_flag_disabled	= 0,
	Freq_hopping_flag_enabled	= 1
} e_Freq_hopping_flag;

/* Freq-hopping-flag */
typedef long	 Freq_hopping_flag_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Freq_hopping_flag_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Freq_hopping_flag;
extern const asn_INTEGER_specifics_t asn_SPC_Freq_hopping_flag_specs_1;
asn_struct_free_f Freq_hopping_flag_free;
asn_struct_print_f Freq_hopping_flag_print;
asn_constr_check_f Freq_hopping_flag_constraint;
ber_type_decoder_f Freq_hopping_flag_decode_ber;
der_type_encoder_f Freq_hopping_flag_encode_der;
xer_type_decoder_f Freq_hopping_flag_decode_xer;
xer_type_encoder_f Freq_hopping_flag_encode_xer;
oer_type_decoder_f Freq_hopping_flag_decode_oer;
oer_type_encoder_f Freq_hopping_flag_encode_oer;
per_type_decoder_f Freq_hopping_flag_decode_uper;
per_type_encoder_f Freq_hopping_flag_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Freq_hopping_flag_H_ */
#include <asn_internal.h>
