/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Intra-Frequency-Cell-Reselection"
 * 	found in "LTE_ML1_Intra_Frequency_Cell_Reselection.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Idle_Meas_Serving_Freq_Resel_Info_H_
#define	_Idle_Meas_Serving_Freq_Resel_Info_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Idle-Meas-Serving-Freq-Resel-Info */
typedef struct Idle_Meas_Serving_Freq_Resel_Info {
	long	 standards_version;
	OCTET_STRING_t	 skip4;
	long	 serving_cell_priority;
	long	 s_non_intra_search;
	long	 thresh_serving_low;
	BIT_STRING_t	 skip5;
	long	 s_non_intra_search_q;
	long	 thresh_serving_low_q;
	OCTET_STRING_t	 skip6;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Idle_Meas_Serving_Freq_Resel_Info_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Idle_Meas_Serving_Freq_Resel_Info;
extern asn_SEQUENCE_specifics_t asn_SPC_Idle_Meas_Serving_Freq_Resel_Info_specs_1;
extern asn_TYPE_member_t asn_MBR_Idle_Meas_Serving_Freq_Resel_Info_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _Idle_Meas_Serving_Freq_Resel_Info_H_ */
#include <asn_internal.h>
