/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Intra-Frequency-Cell-Reselection"
 * 	found in "LTE_ML1_Intra_Frequency_Cell_Reselection.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Idle_Mode_Resel_Meas_LTE_Frequency_H_
#define	_Idle_Mode_Resel_Meas_LTE_Frequency_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Idle-Mode-Resel-Meas-LTE-Frequency */
typedef struct Idle_Mode_Resel_Meas_LTE_Frequency {
	OCTET_STRING_t	 skip7;
	long	 instance;
	long	 number_of_layers;
	long	 treselection;
	OCTET_STRING_t	 skip8;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Idle_Mode_Resel_Meas_LTE_Frequency_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Idle_Mode_Resel_Meas_LTE_Frequency;
extern asn_SEQUENCE_specifics_t asn_SPC_Idle_Mode_Resel_Meas_LTE_Frequency_specs_1;
extern asn_TYPE_member_t asn_MBR_Idle_Mode_Resel_Meas_LTE_Frequency_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _Idle_Mode_Resel_Meas_LTE_Frequency_H_ */
#include <asn_internal.h>
