/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-LL1-Serving-Cell-Measurement-Results"
 * 	found in "LTE_LL1_Serving_Cell_Measurement_Results.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Is_Idle_Mode_H_
#define	_Is_Idle_Mode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Is_Idle_Mode {
	Is_Idle_Mode_connected_Mode	= 0,
	Is_Idle_Mode_unknown1	= 1,
	Is_Idle_Mode_unknown2	= 2
} e_Is_Idle_Mode;

/* Is-Idle-Mode */
typedef long	 Is_Idle_Mode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Is_Idle_Mode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Is_Idle_Mode;
extern const asn_INTEGER_specifics_t asn_SPC_Is_Idle_Mode_specs_1;
asn_struct_free_f Is_Idle_Mode_free;
asn_struct_print_f Is_Idle_Mode_print;
asn_constr_check_f Is_Idle_Mode_constraint;
ber_type_decoder_f Is_Idle_Mode_decode_ber;
der_type_encoder_f Is_Idle_Mode_encode_der;
xer_type_decoder_f Is_Idle_Mode_decode_xer;
xer_type_encoder_f Is_Idle_Mode_encode_xer;
oer_type_decoder_f Is_Idle_Mode_decode_oer;
oer_type_encoder_f Is_Idle_Mode_encode_oer;
per_type_decoder_f Is_Idle_Mode_decode_uper;
per_type_encoder_f Is_Idle_Mode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Is_Idle_Mode_H_ */
#include <asn_internal.h>
