/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-LL1-Serving-Cell-Measurement-Results"
 * 	found in "LTE_LL1_Serving_Cell_Measurement_Results.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "Is-Idle-Mode.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_Is_Idle_Mode_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_Is_Idle_Mode_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_Is_Idle_Mode_value2enum_1[] = {
	{ 0,	14,	"connected-Mode" },
	{ 1,	8,	"unknown1" },
	{ 2,	8,	"unknown2" }
};
static const unsigned int asn_MAP_Is_Idle_Mode_enum2value_1[] = {
	0,	/* connected-Mode(0) */
	1,	/* unknown1(1) */
	2	/* unknown2(2) */
};
const asn_INTEGER_specifics_t asn_SPC_Is_Idle_Mode_specs_1 = {
	asn_MAP_Is_Idle_Mode_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_Is_Idle_Mode_enum2value_1,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_Is_Idle_Mode_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Is_Idle_Mode = {
	"Is-Idle-Mode",
	"Is-Idle-Mode",
	&asn_OP_NativeEnumerated,
	asn_DEF_Is_Idle_Mode_tags_1,
	sizeof(asn_DEF_Is_Idle_Mode_tags_1)
		/sizeof(asn_DEF_Is_Idle_Mode_tags_1[0]), /* 1 */
	asn_DEF_Is_Idle_Mode_tags_1,	/* Same as above */
	sizeof(asn_DEF_Is_Idle_Mode_tags_1)
		/sizeof(asn_DEF_Is_Idle_Mode_tags_1[0]), /* 1 */
	{ &asn_OER_type_Is_Idle_Mode_constr_1, &asn_PER_type_Is_Idle_Mode_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_Is_Idle_Mode_specs_1	/* Additional specs */
};

