/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Intra-Frequency-Cell-Reselection"
 * 	found in "LTE_ML1_Intra_Frequency_Cell_Reselection.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "LTE-ML1-Intra-Frequency-Cell-Reselection-pkt-11-layer.h"

static int
eARFCN_2_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
memb_eARFCN_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_qoffset_frequency_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 5)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_treselection_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 7)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_number_of_cells_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_thresh_x_high_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_thresh_x_low_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_priority_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip9_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_eARFCN_constr_2 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_eARFCN_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_eARFCN_constr_2 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_eARFCN_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_qoffset_frequency_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	5	/* (SIZE(5..5)) */};
static asn_per_constraints_t asn_PER_memb_qoffset_frequency_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  5,  5 }	/* (SIZE(5..5)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_treselection_constr_4 CC_NOTUSED = {
	{ 1, 1 }	/* (0..7) */,
	-1};
static asn_per_constraints_t asn_PER_memb_treselection_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_number_of_cells_constr_5 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_number_of_cells_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_thresh_x_high_constr_6 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_thresh_x_high_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_thresh_x_low_constr_7 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_thresh_x_low_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_priority_constr_8 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_priority_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip9_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	3	/* (SIZE(3..3)) */};
static asn_per_constraints_t asn_PER_memb_skip9_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  3,  3 }	/* (SIZE(3..3)) */,
	0, 0	/* No PER value map */
};
static const asn_INTEGER_specifics_t asn_SPC_eARFCN_specs_2 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_eARFCN_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eARFCN_2 = {
	"eARFCN",
	"eARFCN",
	&asn_OP_NativeInteger,
	asn_DEF_eARFCN_tags_2,
	sizeof(asn_DEF_eARFCN_tags_2)
		/sizeof(asn_DEF_eARFCN_tags_2[0]), /* 1 */
	asn_DEF_eARFCN_tags_2,	/* Same as above */
	sizeof(asn_DEF_eARFCN_tags_2)
		/sizeof(asn_DEF_eARFCN_tags_2[0]), /* 1 */
	{ &asn_OER_type_eARFCN_constr_2, &asn_PER_type_eARFCN_constr_2, eARFCN_2_constraint },
	0, 0,	/* No members */
	&asn_SPC_eARFCN_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer, eARFCN),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_eARFCN_2,
		0,
		{ &asn_OER_memb_eARFCN_constr_2, &asn_PER_memb_eARFCN_constr_2,  memb_eARFCN_constraint_1 },
		0, 0, /* No default value */
		"eARFCN"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer, qoffset_frequency),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_qoffset_frequency_constr_3, &asn_PER_memb_qoffset_frequency_constr_3,  memb_qoffset_frequency_constraint_1 },
		0, 0, /* No default value */
		"qoffset-frequency"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer, treselection),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_treselection_constr_4, &asn_PER_memb_treselection_constr_4,  memb_treselection_constraint_1 },
		0, 0, /* No default value */
		"treselection"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer, number_of_cells),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_number_of_cells_constr_5, &asn_PER_memb_number_of_cells_constr_5,  memb_number_of_cells_constraint_1 },
		0, 0, /* No default value */
		"number-of-cells"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer, thresh_x_high),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_thresh_x_high_constr_6, &asn_PER_memb_thresh_x_high_constr_6,  memb_thresh_x_high_constraint_1 },
		0, 0, /* No default value */
		"thresh-x-high"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer, thresh_x_low),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_thresh_x_low_constr_7, &asn_PER_memb_thresh_x_low_constr_7,  memb_thresh_x_low_constraint_1 },
		0, 0, /* No default value */
		"thresh-x-low"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer, priority),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_priority_constr_8, &asn_PER_memb_priority_constr_8,  memb_priority_constraint_1 },
		0, 0, /* No default value */
		"priority"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer, skip9),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_skip9_constr_9, &asn_PER_memb_skip9_constr_9,  memb_skip9_constraint_1 },
		0, 0, /* No default value */
		"skip9"
		},
};
static const ber_tlv_tag_t asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 5 }, /* eARFCN */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -1, 4 }, /* treselection */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, -2, 3 }, /* number-of-cells */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, -3, 2 }, /* thresh-x-high */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 5, -4, 1 }, /* thresh-x-low */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 6, -5, 0 }, /* priority */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 1, 0, 0 }, /* qoffset-frequency */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 7, 0, 0 } /* skip9 */
};
static asn_SEQUENCE_specifics_t asn_SPC_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer_specs_1 = {
	sizeof(struct LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer),
	offsetof(struct LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer, _asn_ctx),
	asn_MAP_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer = {
	"LTE-ML1-Intra-Frequency-Cell-Reselection-pkt-11-layer",
	"LTE-ML1-Intra-Frequency-Cell-Reselection-pkt-11-layer",
	&asn_OP_SEQUENCE,
	asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer_tags_1,
	sizeof(asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer_tags_1)
		/sizeof(asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer_tags_1[0]), /* 1 */
	asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer_tags_1,	/* Same as above */
	sizeof(asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer_tags_1)
		/sizeof(asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer_1,
	8,	/* Elements count */
	&asn_SPC_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer_specs_1	/* Additional specs */
};

