/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Serving-Cell-Information"
 * 	found in "LTE_ML1_Serving_Cell_Information.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_LTE_ML1_Serving_Cell_Information_S_H_H_
#define	_LTE_ML1_Serving_Cell_Information_S_H_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "Dl-bandwidth.h"
#include <BIT_STRING.h>
#include <OCTET_STRING.h>
#include <INTEGER.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LTE-ML1-Serving-Cell-Information-S-H */
typedef struct LTE_ML1_Serving_Cell_Information_S_H {
	long	 version;
	Dl_bandwidth_t	 dl_bandwidth;
	BIT_STRING_t	 skip0;
	long	 sfn;
	unsigned long	 e_arfcn;
	long	 pHICH_Resource;
	long	 pHICH_Duration;
	long	 pBCH_Decode_Result;
	long	 physical_cell_id;
	long	 pSS_Correlation;
	OCTET_STRING_t	 skip1;
	long	 sSS_Correlation;
	OCTET_STRING_t	 skip2;
	INTEGER_t	 ref_time;
	OCTET_STRING_t	 skip3;
	unsigned long	 mIB_payload;
	long	 freq_Offset;
	BIT_STRING_t	 skip4;
	long	 num_Antennas;
	BIT_STRING_t	 skip5;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_ML1_Serving_Cell_Information_S_H_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_e_arfcn_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_mIB_payload_17;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LTE_ML1_Serving_Cell_Information_S_H;

#ifdef __cplusplus
}
#endif

#endif	/* _LTE_ML1_Serving_Cell_Information_S_H_H_ */
#include <asn_internal.h>
