/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-AdvRx-IC-Cell-List"
 * 	found in "LTE_ML1_AdvRx_IC_Cell_List.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_LTE_ML1_AdvRx_IC_Cell_List_S_H_H_
#define	_LTE_ML1_AdvRx_IC_Cell_List_S_H_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "Carrier-index.h"
#include <BIT_STRING.h>
#include "ENB-Type.h"
#include "Fw-mode.h"
#include <OCTET_STRING.h>
#include "Serving.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LTE-ML1-AdvRx-IC-Cell-List-S-H */
typedef struct LTE_ML1_AdvRx_IC_Cell_List_S_H {
	long	 version;
	Carrier_index_t	 carrier_index;
	BIT_STRING_t	 skip0;
	ENB_Type_t	 eNB_Type;
	BIT_STRING_t	 skip1;
	Fw_mode_t	 fw_mode;
	BIT_STRING_t	 skip15;
	unsigned long	 earfcn_data;
	OCTET_STRING_t	 skip2;
	long	 num_Neighbors;
	BIT_STRING_t	 skip3;
	long	 panic_escape_mask;
	long	 valid_Sched_Rate;
	long	 is_Carrier_Cfg_FW;
	long	 sub_fn;
	long	 tm_Mode;
	OCTET_STRING_t	 skip5;
	Serving_t	 serving;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_ML1_AdvRx_IC_Cell_List_S_H_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_earfcn_data_9;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LTE_ML1_AdvRx_IC_Cell_List_S_H;

#ifdef __cplusplus
}
#endif

#endif	/* _LTE_ML1_AdvRx_IC_Cell_List_S_H_H_ */
#include <asn_internal.h>
