/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-GM-TX-Report"
 * 	found in "LTE_ML1_GM_TX_Report.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "LTE-ML1-GM-TX-Report-R-H.h"

static int
memb_skip1_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 4)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_csf_present_flag_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip2_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_tx_sub_fn_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_tx_sys_fn_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1023)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip3_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 4)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_cell_index_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_srs_present_flag_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip4_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_srs_ue_cell_specific_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_skip1_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	4	/* (SIZE(4..4)) */};
static asn_per_constraints_t asn_PER_memb_skip1_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  4,  4 }	/* (SIZE(4..4)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_csf_present_flag_constr_3 CC_NOTUSED = {
	{ 1, 1 }	/* (0..1) */,
	-1};
static asn_per_constraints_t asn_PER_memb_csf_present_flag_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip2_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	1	/* (SIZE(1..1)) */};
static asn_per_constraints_t asn_PER_memb_skip2_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  1,  1 }	/* (SIZE(1..1)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_tx_sub_fn_constr_7 CC_NOTUSED = {
	{ 1, 1 }	/* (0..15) */,
	-1};
static asn_per_constraints_t asn_PER_memb_tx_sub_fn_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_tx_sys_fn_constr_8 CC_NOTUSED = {
	{ 2, 1 }	/* (0..1023) */,
	-1};
static asn_per_constraints_t asn_PER_memb_tx_sys_fn_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 10,  10,  0,  1023 }	/* (0..1023) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip3_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	4	/* (SIZE(4..4)) */};
static asn_per_constraints_t asn_PER_memb_skip3_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  4,  4 }	/* (SIZE(4..4)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_cell_index_constr_10 CC_NOTUSED = {
	{ 1, 1 }	/* (0..3) */,
	-1};
static asn_per_constraints_t asn_PER_memb_cell_index_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_srs_present_flag_constr_11 CC_NOTUSED = {
	{ 1, 1 }	/* (0..1) */,
	-1};
static asn_per_constraints_t asn_PER_memb_srs_present_flag_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip4_constr_12 CC_NOTUSED = {
	{ 0, 0 },
	3	/* (SIZE(3..3)) */};
static asn_per_constraints_t asn_PER_memb_skip4_constr_12 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  3,  3 }	/* (SIZE(3..3)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_srs_ue_cell_specific_constr_14 CC_NOTUSED = {
	{ 1, 1 }	/* (0..1) */,
	-1};
static asn_per_constraints_t asn_PER_memb_srs_ue_cell_specific_constr_14 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_LTE_ML1_GM_TX_Report_R_H_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_GM_TX_Report_R_H, skip1),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_skip1_constr_2, &asn_PER_memb_skip1_constr_2,  memb_skip1_constraint_1 },
		0, 0, /* No default value */
		"skip1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_GM_TX_Report_R_H, csf_present_flag),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_csf_present_flag_constr_3, &asn_PER_memb_csf_present_flag_constr_3,  memb_csf_present_flag_constraint_1 },
		0, 0, /* No default value */
		"csf-present-flag"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_GM_TX_Report_R_H, ack_nak_reporting_mode),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_Ack_nak_reporting_mode,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ack-nak-reporting-mode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_GM_TX_Report_R_H, skip2),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip2_constr_5, &asn_PER_memb_skip2_constr_5,  memb_skip2_constraint_1 },
		0, 0, /* No default value */
		"skip2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_GM_TX_Report_R_H, ul_ack_nak_present_flag),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_Ul_ack_nak_present_flag,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ul-ack-nak-present-flag"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_GM_TX_Report_R_H, tx_sub_fn),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_tx_sub_fn_constr_7, &asn_PER_memb_tx_sub_fn_constr_7,  memb_tx_sub_fn_constraint_1 },
		0, 0, /* No default value */
		"tx-sub-fn"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_GM_TX_Report_R_H, tx_sys_fn),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_tx_sys_fn_constr_8, &asn_PER_memb_tx_sys_fn_constr_8,  memb_tx_sys_fn_constraint_1 },
		0, 0, /* No default value */
		"tx-sys-fn"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_GM_TX_Report_R_H, skip3),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip3_constr_9, &asn_PER_memb_skip3_constr_9,  memb_skip3_constraint_1 },
		0, 0, /* No default value */
		"skip3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_GM_TX_Report_R_H, cell_index),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_cell_index_constr_10, &asn_PER_memb_cell_index_constr_10,  memb_cell_index_constraint_1 },
		0, 0, /* No default value */
		"cell-index"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_GM_TX_Report_R_H, srs_present_flag),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_srs_present_flag_constr_11, &asn_PER_memb_srs_present_flag_constr_11,  memb_srs_present_flag_constraint_1 },
		0, 0, /* No default value */
		"srs-present-flag"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_GM_TX_Report_R_H, skip4),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip4_constr_12, &asn_PER_memb_skip4_constr_12,  memb_skip4_constraint_1 },
		0, 0, /* No default value */
		"skip4"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_GM_TX_Report_R_H, ca_mode_enabled),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_Ca_mode_enabled,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ca-mode-enabled"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_GM_TX_Report_R_H, srs_ue_cell_specific),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_srs_ue_cell_specific_constr_14, &asn_PER_memb_srs_ue_cell_specific_constr_14,  memb_srs_ue_cell_specific_constraint_1 },
		0, 0, /* No default value */
		"srs-ue-cell-specific"
		},
};
static const ber_tlv_tag_t asn_DEF_LTE_ML1_GM_TX_Report_R_H_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LTE_ML1_GM_TX_Report_R_H_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 5 }, /* csf-present-flag */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 5, -1, 4 }, /* tx-sub-fn */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 6, -2, 3 }, /* tx-sys-fn */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 8, -3, 2 }, /* cell-index */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 9, -4, 1 }, /* srs-present-flag */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 12, -5, 0 }, /* srs-ue-cell-specific */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 3, 0, 2 }, /* skip2 */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 7, -1, 1 }, /* skip3 */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 10, -2, 0 }, /* skip4 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 }, /* skip1 */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 2, 0, 2 }, /* ack-nak-reporting-mode */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 4, -1, 1 }, /* ul-ack-nak-present-flag */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 11, -2, 0 } /* ca-mode-enabled */
};
static asn_SEQUENCE_specifics_t asn_SPC_LTE_ML1_GM_TX_Report_R_H_specs_1 = {
	sizeof(struct LTE_ML1_GM_TX_Report_R_H),
	offsetof(struct LTE_ML1_GM_TX_Report_R_H, _asn_ctx),
	asn_MAP_LTE_ML1_GM_TX_Report_R_H_tag2el_1,
	13,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LTE_ML1_GM_TX_Report_R_H = {
	"LTE-ML1-GM-TX-Report-R-H",
	"LTE-ML1-GM-TX-Report-R-H",
	&asn_OP_SEQUENCE,
	asn_DEF_LTE_ML1_GM_TX_Report_R_H_tags_1,
	sizeof(asn_DEF_LTE_ML1_GM_TX_Report_R_H_tags_1)
		/sizeof(asn_DEF_LTE_ML1_GM_TX_Report_R_H_tags_1[0]), /* 1 */
	asn_DEF_LTE_ML1_GM_TX_Report_R_H_tags_1,	/* Same as above */
	sizeof(asn_DEF_LTE_ML1_GM_TX_Report_R_H_tags_1)
		/sizeof(asn_DEF_LTE_ML1_GM_TX_Report_R_H_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LTE_ML1_GM_TX_Report_R_H_1,
	13,	/* Elements count */
	&asn_SPC_LTE_ML1_GM_TX_Report_R_H_specs_1	/* Additional specs */
};

