/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Idle-Measurement-Request"
 * 	found in "LTE_ML1_Idle_Measurement_Request.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "LTE-ML1-Idle-Measurement-Request-Sub-Pkt-7-cell.h"

static int
memb_q_Offset_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 127)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_physical_Cell_ID_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 511)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_q_Offset_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..127) */,
	-1};
static asn_per_constraints_t asn_PER_memb_q_Offset_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  127 }	/* (0..127) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_physical_Cell_ID_constr_3 CC_NOTUSED = {
	{ 2, 1 }	/* (0..511) */,
	-1};
static asn_per_constraints_t asn_PER_memb_physical_Cell_ID_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 9,  9,  0,  511 }	/* (0..511) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_cell_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_cell, q_Offset),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_q_Offset_constr_2, &asn_PER_memb_q_Offset_constr_2,  memb_q_Offset_constraint_1 },
		0, 0, /* No default value */
		"q-Offset"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_cell, physical_Cell_ID),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_physical_Cell_ID_constr_3, &asn_PER_memb_physical_Cell_ID_constr_3,  memb_physical_Cell_ID_constraint_1 },
		0, 0, /* No default value */
		"physical-Cell-ID"
		},
};
static const ber_tlv_tag_t asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_cell_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_cell_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* q-Offset */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 } /* physical-Cell-ID */
};
static asn_SEQUENCE_specifics_t asn_SPC_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_cell_specs_1 = {
	sizeof(struct LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_cell),
	offsetof(struct LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_cell, _asn_ctx),
	asn_MAP_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_cell_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_cell = {
	"LTE-ML1-Idle-Measurement-Request-Sub-Pkt-7-cell",
	"LTE-ML1-Idle-Measurement-Request-Sub-Pkt-7-cell",
	&asn_OP_SEQUENCE,
	asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_cell_tags_1,
	sizeof(asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_cell_tags_1)
		/sizeof(asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_cell_tags_1[0]), /* 1 */
	asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_cell_tags_1,	/* Same as above */
	sizeof(asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_cell_tags_1)
		/sizeof(asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_cell_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_cell_1,
	2,	/* Elements count */
	&asn_SPC_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_cell_specs_1	/* Additional specs */
};

