/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Idle-Measurement-Request"
 * 	found in "LTE_ML1_Idle_Measurement_Request.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "LTE-ML1-Idle-Measurement-Request-Sub-Pkt-5.h"

static int
memb_version_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_subpacket_size_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip2_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 8)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_version_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_version_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_subpacket_size_constr_3 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_subpacket_size_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip2_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	8	/* (SIZE(8..8)) */};
static asn_per_constraints_t asn_PER_memb_skip2_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  8,  8 }	/* (SIZE(8..8)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_version_constr_2, &asn_PER_memb_version_constr_2,  memb_version_constraint_1 },
		0, 0, /* No default value */
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5, subpacket_size),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_subpacket_size_constr_3, &asn_PER_memb_subpacket_size_constr_3,  memb_subpacket_size_constraint_1 },
		0, 0, /* No default value */
		"subpacket-size"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5, skip2),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip2_constr_4, &asn_PER_memb_skip2_constr_4,  memb_skip2_constraint_1 },
		0, 0, /* No default value */
		"skip2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5, subPacket_Idle_Meas_Serving_Frequency_Resel_Info),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SubPacket_Idle_Meas_Serving_Frequency_Resel_Info,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subPacket-Idle-Meas-Serving-Frequency-Resel-Info"
		},
};
static const ber_tlv_tag_t asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* version */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 }, /* subpacket-size */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 2, 0, 0 }, /* skip2 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, 0, 0 } /* subPacket-Idle-Meas-Serving-Frequency-Resel-Info */
};
static asn_SEQUENCE_specifics_t asn_SPC_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5_specs_1 = {
	sizeof(struct LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5),
	offsetof(struct LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5, _asn_ctx),
	asn_MAP_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5 = {
	"LTE-ML1-Idle-Measurement-Request-Sub-Pkt-5",
	"LTE-ML1-Idle-Measurement-Request-Sub-Pkt-5",
	&asn_OP_SEQUENCE,
	asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5_tags_1,
	sizeof(asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5_tags_1)
		/sizeof(asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5_tags_1[0]), /* 1 */
	asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5_tags_1,	/* Same as above */
	sizeof(asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5_tags_1)
		/sizeof(asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5_1,
	4,	/* Elements count */
	&asn_SPC_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5_specs_1	/* Additional specs */
};

