/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Intra-Frequency-Cell-Reselection"
 * 	found in "LTE_ML1_Intra_Frequency_Cell_Reselection.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "LTE-ML1-Intra-Frequency-Cell-Reselection-pkt-5.h"

static asn_TYPE_member_t asn_MBR_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_5_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_5, idle_Meas_Serving_Freq_Resel_Info),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Idle_Meas_Serving_Freq_Resel_Info,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"idle-Meas-Serving-Freq-Resel-Info"
		},
};
static const ber_tlv_tag_t asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_5_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_5_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* idle-Meas-Serving-Freq-Resel-Info */
};
static asn_SEQUENCE_specifics_t asn_SPC_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_5_specs_1 = {
	sizeof(struct LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_5),
	offsetof(struct LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_5, _asn_ctx),
	asn_MAP_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_5_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_5 = {
	"LTE-ML1-Intra-Frequency-Cell-Reselection-pkt-5",
	"LTE-ML1-Intra-Frequency-Cell-Reselection-pkt-5",
	&asn_OP_SEQUENCE,
	asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_5_tags_1,
	sizeof(asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_5_tags_1)
		/sizeof(asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_5_tags_1[0]), /* 1 */
	asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_5_tags_1,	/* Same as above */
	sizeof(asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_5_tags_1)
		/sizeof(asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_5_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_5_1,
	1,	/* Elements count */
	&asn_SPC_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_5_specs_1	/* Additional specs */
};

