/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Random-Access-Response-MSG2-Report"
 * 	found in "LTE_ML1_Random_Access_Response_MSG2_Report.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_LTE_ML1_Random_Access_Response_MSG2_Report_S_H_H_
#define	_LTE_ML1_Random_Access_Response_MSG2_Report_S_H_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include "LTE-ML1-Random-Access-Response-MSG2-Report_Carrier-Type.h"
#include "Timing-advance-included.h"
#include "Rach-procedure-type.h"
#include "RACH-Procedure-Mode.h"
#include "RNTI-Type.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LTE-ML1-Random-Access-Response-MSG2-Report-S-H */
typedef struct LTE_ML1_Random_Access_Response_MSG2_Report_S_H {
	long	 version;
	BIT_STRING_t	 skip0;
	LTE_ML1_Random_Access_Response_MSG2_Report_Carrier_Type_t	 cell_index;
	BIT_STRING_t	 skip1;
	long	 rnti_value;
	Timing_advance_included_t	 timing_advance_included;
	Rach_procedure_type_t	 rach_procedure_type;
	RACH_Procedure_Mode_t	 rACH_Procedure_Mode;
	RNTI_Type_t	 rNTI_Type;
	long	 system_frame_number;
	BIT_STRING_t	 skip2;
	long	 sub_frame_number;
	long	 tIMING_ADVANCE;
	BIT_STRING_t	 skip3;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_ML1_Random_Access_Response_MSG2_Report_S_H_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LTE_ML1_Random_Access_Response_MSG2_Report_S_H;

#ifdef __cplusplus
}
#endif

#endif	/* _LTE_ML1_Random_Access_Response_MSG2_Report_S_H_H_ */
#include <asn_internal.h>
