/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-PDCP-DL-Data-PDU"
 * 	found in "LTE_PDCP_DL_Data_PDU.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "LTE-PDCP-DL-Data-PDU-Meta-Log-Buffer.h"

static int
rx_timetick_raw_4_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
memb_sub_fn_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_sfn_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_rx_timetick_raw_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_skip5_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 5)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_rb_cfg_index_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_key_index_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip6_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 7)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip7_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 7)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ip_packet_header0_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ip_packet_header1_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_startcount_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip8_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 2)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_endcount_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip9_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 2)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_rlc_end_sn_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip10_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 2)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_number_ip_pkts_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip11_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_number_ip_bytes_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip12_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 2)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_rx_timetick_raw_constr_4 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_rx_timetick_raw_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_sub_fn_constr_2 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65535) */,
	-1};
static asn_per_constraints_t asn_PER_memb_sub_fn_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_sfn_constr_3 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65535) */,
	-1};
static asn_per_constraints_t asn_PER_memb_sfn_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_rx_timetick_raw_constr_4 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_rx_timetick_raw_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip5_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	5	/* (SIZE(5..5)) */};
static asn_per_constraints_t asn_PER_memb_skip5_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  5,  5 }	/* (SIZE(5..5)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_rb_cfg_index_constr_6 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_rb_cfg_index_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_key_index_constr_7 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_key_index_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip6_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	7	/* (SIZE(7..7)) */};
static asn_per_constraints_t asn_PER_memb_skip6_constr_8 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  7,  7 }	/* (SIZE(7..7)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip7_constr_10 CC_NOTUSED = {
	{ 0, 0 },
	7	/* (SIZE(7..7)) */};
static asn_per_constraints_t asn_PER_memb_skip7_constr_10 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  7,  7 }	/* (SIZE(7..7)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ip_packet_header0_constr_12 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_ip_packet_header0_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ip_packet_header1_constr_13 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_ip_packet_header1_constr_13 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_startcount_constr_14 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65535) */,
	-1};
static asn_per_constraints_t asn_PER_memb_startcount_constr_14 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip8_constr_15 CC_NOTUSED = {
	{ 0, 0 },
	2	/* (SIZE(2..2)) */};
static asn_per_constraints_t asn_PER_memb_skip8_constr_15 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  2,  2 }	/* (SIZE(2..2)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_endcount_constr_16 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65535) */,
	-1};
static asn_per_constraints_t asn_PER_memb_endcount_constr_16 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip9_constr_17 CC_NOTUSED = {
	{ 0, 0 },
	2	/* (SIZE(2..2)) */};
static asn_per_constraints_t asn_PER_memb_skip9_constr_17 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  2,  2 }	/* (SIZE(2..2)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_rlc_end_sn_constr_18 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65535) */,
	-1};
static asn_per_constraints_t asn_PER_memb_rlc_end_sn_constr_18 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip10_constr_19 CC_NOTUSED = {
	{ 0, 0 },
	2	/* (SIZE(2..2)) */};
static asn_per_constraints_t asn_PER_memb_skip10_constr_19 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  2,  2 }	/* (SIZE(2..2)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_number_ip_pkts_constr_20 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_number_ip_pkts_constr_20 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip11_constr_21 CC_NOTUSED = {
	{ 0, 0 },
	3	/* (SIZE(3..3)) */};
static asn_per_constraints_t asn_PER_memb_skip11_constr_21 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  3,  3 }	/* (SIZE(3..3)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_number_ip_bytes_constr_22 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65535) */,
	-1};
static asn_per_constraints_t asn_PER_memb_number_ip_bytes_constr_22 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip12_constr_23 CC_NOTUSED = {
	{ 0, 0 },
	2	/* (SIZE(2..2)) */};
static asn_per_constraints_t asn_PER_memb_skip12_constr_23 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  2,  2 }	/* (SIZE(2..2)) */,
	0, 0	/* No PER value map */
};
static const asn_INTEGER_specifics_t asn_SPC_rx_timetick_raw_specs_4 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_rx_timetick_raw_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_rx_timetick_raw_4 = {
	"rx-timetick-raw",
	"rx-timetick-raw",
	&asn_OP_NativeInteger,
	asn_DEF_rx_timetick_raw_tags_4,
	sizeof(asn_DEF_rx_timetick_raw_tags_4)
		/sizeof(asn_DEF_rx_timetick_raw_tags_4[0]), /* 1 */
	asn_DEF_rx_timetick_raw_tags_4,	/* Same as above */
	sizeof(asn_DEF_rx_timetick_raw_tags_4)
		/sizeof(asn_DEF_rx_timetick_raw_tags_4[0]), /* 1 */
	{ &asn_OER_type_rx_timetick_raw_constr_4, &asn_PER_type_rx_timetick_raw_constr_4, rx_timetick_raw_4_constraint },
	0, 0,	/* No members */
	&asn_SPC_rx_timetick_raw_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, sub_fn),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_sub_fn_constr_2, &asn_PER_memb_sub_fn_constr_2,  memb_sub_fn_constraint_1 },
		0, 0, /* No default value */
		"sub-fn"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, sfn),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_sfn_constr_3, &asn_PER_memb_sfn_constr_3,  memb_sfn_constraint_1 },
		0, 0, /* No default value */
		"sfn"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, rx_timetick_raw),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_rx_timetick_raw_4,
		0,
		{ &asn_OER_memb_rx_timetick_raw_constr_4, &asn_PER_memb_rx_timetick_raw_constr_4,  memb_rx_timetick_raw_constraint_1 },
		0, 0, /* No default value */
		"rx-timetick-raw"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, skip5),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_skip5_constr_5, &asn_PER_memb_skip5_constr_5,  memb_skip5_constraint_1 },
		0, 0, /* No default value */
		"skip5"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, rb_cfg_index),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_rb_cfg_index_constr_6, &asn_PER_memb_rb_cfg_index_constr_6,  memb_rb_cfg_index_constraint_1 },
		0, 0, /* No default value */
		"rb-cfg-index"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, key_index),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_key_index_constr_7, &asn_PER_memb_key_index_constr_7,  memb_key_index_constraint_1 },
		0, 0, /* No default value */
		"key-index"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, skip6),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip6_constr_8, &asn_PER_memb_skip6_constr_8,  memb_skip6_constraint_1 },
		0, 0, /* No default value */
		"skip6"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, rlc_path),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_Rlcpath,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rlc-path"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, skip7),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip7_constr_10, &asn_PER_memb_skip7_constr_10,  memb_skip7_constraint_1 },
		0, 0, /* No default value */
		"skip7"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, route_status),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_Routestatus,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"route-status"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, ip_packet_header0),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_ip_packet_header0_constr_12, &asn_PER_memb_ip_packet_header0_constr_12,  memb_ip_packet_header0_constraint_1 },
		0, 0, /* No default value */
		"ip-packet-header0"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, ip_packet_header1),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_ip_packet_header1_constr_13, &asn_PER_memb_ip_packet_header1_constr_13,  memb_ip_packet_header1_constraint_1 },
		0, 0, /* No default value */
		"ip-packet-header1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, startcount),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_startcount_constr_14, &asn_PER_memb_startcount_constr_14,  memb_startcount_constraint_1 },
		0, 0, /* No default value */
		"startcount"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, skip8),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_skip8_constr_15, &asn_PER_memb_skip8_constr_15,  memb_skip8_constraint_1 },
		0, 0, /* No default value */
		"skip8"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, endcount),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_endcount_constr_16, &asn_PER_memb_endcount_constr_16,  memb_endcount_constraint_1 },
		0, 0, /* No default value */
		"endcount"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, skip9),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_skip9_constr_17, &asn_PER_memb_skip9_constr_17,  memb_skip9_constraint_1 },
		0, 0, /* No default value */
		"skip9"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, rlc_end_sn),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_rlc_end_sn_constr_18, &asn_PER_memb_rlc_end_sn_constr_18,  memb_rlc_end_sn_constraint_1 },
		0, 0, /* No default value */
		"rlc-end-sn"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, skip10),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_skip10_constr_19, &asn_PER_memb_skip10_constr_19,  memb_skip10_constraint_1 },
		0, 0, /* No default value */
		"skip10"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, number_ip_pkts),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_number_ip_pkts_constr_20, &asn_PER_memb_number_ip_pkts_constr_20,  memb_number_ip_pkts_constraint_1 },
		0, 0, /* No default value */
		"number-ip-pkts"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, skip11),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_skip11_constr_21, &asn_PER_memb_skip11_constr_21,  memb_skip11_constraint_1 },
		0, 0, /* No default value */
		"skip11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, number_ip_bytes),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_number_ip_bytes_constr_22, &asn_PER_memb_number_ip_bytes_constr_22,  memb_number_ip_bytes_constraint_1 },
		0, 0, /* No default value */
		"number-ip-bytes"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, skip12),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_skip12_constr_23, &asn_PER_memb_skip12_constr_23,  memb_skip12_constraint_1 },
		0, 0, /* No default value */
		"skip12"
		},
};
static const ber_tlv_tag_t asn_DEF_LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 11 }, /* sub-fn */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 10 }, /* sfn */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -2, 9 }, /* rx-timetick-raw */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, -3, 8 }, /* rb-cfg-index */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 5, -4, 7 }, /* key-index */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 10, -5, 6 }, /* ip-packet-header0 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 11, -6, 5 }, /* ip-packet-header1 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 12, -7, 4 }, /* startcount */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 14, -8, 3 }, /* endcount */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 16, -9, 2 }, /* rlc-end-sn */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 18, -10, 1 }, /* number-ip-pkts */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 20, -11, 0 }, /* number-ip-bytes */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 6, 0, 1 }, /* skip6 */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 8, -1, 0 }, /* skip7 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 3, 0, 5 }, /* skip5 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 13, -1, 4 }, /* skip8 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 15, -2, 3 }, /* skip9 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 17, -3, 2 }, /* skip10 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 19, -4, 1 }, /* skip11 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 21, -5, 0 }, /* skip12 */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 7, 0, 1 }, /* rlc-path */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 9, -1, 0 } /* route-status */
};
static asn_SEQUENCE_specifics_t asn_SPC_LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer_specs_1 = {
	sizeof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer),
	offsetof(struct LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer, _asn_ctx),
	asn_MAP_LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer_tag2el_1,
	22,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer = {
	"LTE-PDCP-DL-Data-PDU-Meta-Log-Buffer",
	"LTE-PDCP-DL-Data-PDU-Meta-Log-Buffer",
	&asn_OP_SEQUENCE,
	asn_DEF_LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer_tags_1,
	sizeof(asn_DEF_LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer_tags_1)
		/sizeof(asn_DEF_LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer_tags_1[0]), /* 1 */
	asn_DEF_LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer_tags_1,	/* Same as above */
	sizeof(asn_DEF_LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer_tags_1)
		/sizeof(asn_DEF_LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer_1,
	22,	/* Elements count */
	&asn_SPC_LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer_specs_1	/* Additional specs */
};

