/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-CA-Metrics-Log-Packet"
 * 	found in "LTE_ML1_CA_Metrics_Log_Packet.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_LTE_ML1_CA_Metrics_Log_Packet_scells_H_
#define	_LTE_ML1_CA_Metrics_Log_Packet_scells_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Scells-start.h"
#include "Pcell-only.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LTE-ML1-CA-Metrics-Log-Packet-scells */
typedef struct LTE_ML1_CA_Metrics_Log_Packet_scells {
	Scells_start_t	 scells_start;
	Pcell_only_t	 total_scell_metrics;
	Pcell_only_t	 ca_conf_scell_metrics;
	Pcell_only_t	 ca_act_scell_metrics;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_ML1_CA_Metrics_Log_Packet_scells_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LTE_ML1_CA_Metrics_Log_Packet_scells;

#ifdef __cplusplus
}
#endif

#endif	/* _LTE_ML1_CA_Metrics_Log_Packet_scells_H_ */
#include <asn_internal.h>
