/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-UE-Identification-Message-MSG3-Report"
 * 	found in "LTE_UE_Identification_Message_MSG3_Report.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "LTE-UE-Identification-Message-MSG3-Report-S-H.h"

static int
memb_version_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip0_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 5)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip1_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 6)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip2_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 8)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_sfn_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1023)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip3_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 4)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_riv_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_sub_fn_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 7)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_tpc_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_redundancy_Version_Index_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_num_Resource_Blocks_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 31)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_starting_Resource_Block_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 127)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip4_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 5)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip5_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 2)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_harq_id_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 7)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip6_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_version_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_version_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip0_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	5	/* (SIZE(5..5)) */};
static asn_per_constraints_t asn_PER_memb_skip0_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  5,  5 }	/* (SIZE(5..5)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip1_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	6	/* (SIZE(6..6)) */};
static asn_per_constraints_t asn_PER_memb_skip1_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  6,  6 }	/* (SIZE(6..6)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip2_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	8	/* (SIZE(8..8)) */};
static asn_per_constraints_t asn_PER_memb_skip2_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  8,  8 }	/* (SIZE(8..8)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_sfn_constr_8 CC_NOTUSED = {
	{ 2, 1 }	/* (0..1023) */,
	-1};
static asn_per_constraints_t asn_PER_memb_sfn_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 10,  10,  0,  1023 }	/* (0..1023) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip3_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	4	/* (SIZE(4..4)) */};
static asn_per_constraints_t asn_PER_memb_skip3_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  4,  4 }	/* (SIZE(4..4)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_riv_constr_10 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_riv_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_sub_fn_constr_11 CC_NOTUSED = {
	{ 1, 1 }	/* (0..7) */,
	-1};
static asn_per_constraints_t asn_PER_memb_sub_fn_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_tpc_constr_14 CC_NOTUSED = {
	{ 1, 1 }	/* (0..3) */,
	-1};
static asn_per_constraints_t asn_PER_memb_tpc_constr_14 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_redundancy_Version_Index_constr_18 CC_NOTUSED = {
	{ 1, 1 }	/* (0..3) */,
	-1};
static asn_per_constraints_t asn_PER_memb_redundancy_Version_Index_constr_18 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_num_Resource_Blocks_constr_19 CC_NOTUSED = {
	{ 1, 1 }	/* (0..31) */,
	-1};
static asn_per_constraints_t asn_PER_memb_num_Resource_Blocks_constr_19 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  0,  31 }	/* (0..31) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_starting_Resource_Block_constr_20 CC_NOTUSED = {
	{ 1, 1 }	/* (0..127) */,
	-1};
static asn_per_constraints_t asn_PER_memb_starting_Resource_Block_constr_20 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  127 }	/* (0..127) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip4_constr_21 CC_NOTUSED = {
	{ 0, 0 },
	5	/* (SIZE(5..5)) */};
static asn_per_constraints_t asn_PER_memb_skip4_constr_21 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  5,  5 }	/* (SIZE(5..5)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip5_constr_22 CC_NOTUSED = {
	{ 0, 0 },
	2	/* (SIZE(2..2)) */};
static asn_per_constraints_t asn_PER_memb_skip5_constr_22 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  2,  2 }	/* (SIZE(2..2)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_harq_id_constr_23 CC_NOTUSED = {
	{ 1, 1 }	/* (0..7) */,
	-1};
static asn_per_constraints_t asn_PER_memb_harq_id_constr_23 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip6_constr_24 CC_NOTUSED = {
	{ 0, 0 },
	3	/* (SIZE(3..3)) */};
static asn_per_constraints_t asn_PER_memb_skip6_constr_24 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  3,  3 }	/* (SIZE(3..3)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_LTE_UE_Identification_Message_MSG3_Report_S_H_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_version_constr_2, &asn_PER_memb_version_constr_2,  memb_version_constraint_1 },
		0, 0, /* No default value */
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, skip0),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip0_constr_3, &asn_PER_memb_skip0_constr_3,  memb_skip0_constraint_1 },
		0, 0, /* No default value */
		"skip0"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, versions_modulation_type),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_LTE_UE_Identification_Message_MSG3_Report_ModulationType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"versions-modulation-type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, skip1),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip1_constr_5, &asn_PER_memb_skip1_constr_5,  memb_skip1_constraint_1 },
		0, 0, /* No default value */
		"skip1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, cell_index),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_LTE_UE_Identification_Message_MSG3_Report_Carrier_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cell-index"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, skip2),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip2_constr_7, &asn_PER_memb_skip2_constr_7,  memb_skip2_constraint_1 },
		0, 0, /* No default value */
		"skip2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, sfn),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_sfn_constr_8, &asn_PER_memb_sfn_constr_8,  memb_sfn_constraint_1 },
		0, 0, /* No default value */
		"sfn"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, skip3),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip3_constr_9, &asn_PER_memb_skip3_constr_9,  memb_skip3_constraint_1 },
		0, 0, /* No default value */
		"skip3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, riv),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_riv_constr_10, &asn_PER_memb_riv_constr_10,  memb_riv_constraint_1 },
		0, 0, /* No default value */
		"riv"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, sub_fn),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_sub_fn_constr_11, &asn_PER_memb_sub_fn_constr_11,  memb_sub_fn_constraint_1 },
		0, 0, /* No default value */
		"sub-fn"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, cqi),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_Cqi,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cqi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, ul_delay),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_Ul_Delay,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ul-delay"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, tpc),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_tpc_constr_14, &asn_PER_memb_tpc_constr_14,  memb_tpc_constraint_1 },
		0, 0, /* No default value */
		"tpc"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, mcs),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_Mcs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mcs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, hopping_flag),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_Hopping_flag,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hopping-flag"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, transport_Block_Size_Index),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_Transport_Block_Size_Index,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transport-Block-Size-Index"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, redundancy_Version_Index),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_redundancy_Version_Index_constr_18, &asn_PER_memb_redundancy_Version_Index_constr_18,  memb_redundancy_Version_Index_constraint_1 },
		0, 0, /* No default value */
		"redundancy-Version-Index"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, num_Resource_Blocks),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_num_Resource_Blocks_constr_19, &asn_PER_memb_num_Resource_Blocks_constr_19,  memb_num_Resource_Blocks_constraint_1 },
		0, 0, /* No default value */
		"num-Resource-Blocks"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, starting_Resource_Block),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_starting_Resource_Block_constr_20, &asn_PER_memb_starting_Resource_Block_constr_20,  memb_starting_Resource_Block_constraint_1 },
		0, 0, /* No default value */
		"starting-Resource-Block"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, skip4),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip4_constr_21, &asn_PER_memb_skip4_constr_21,  memb_skip4_constraint_1 },
		0, 0, /* No default value */
		"skip4"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, skip5),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip5_constr_22, &asn_PER_memb_skip5_constr_22,  memb_skip5_constraint_1 },
		0, 0, /* No default value */
		"skip5"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, harq_id),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_harq_id_constr_23, &asn_PER_memb_harq_id_constr_23,  memb_harq_id_constraint_1 },
		0, 0, /* No default value */
		"harq-id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, skip6),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip6_constr_24, &asn_PER_memb_skip6_constr_24,  memb_skip6_constraint_1 },
		0, 0, /* No default value */
		"skip6"
		},
};
static const ber_tlv_tag_t asn_DEF_LTE_UE_Identification_Message_MSG3_Report_S_H_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LTE_UE_Identification_Message_MSG3_Report_S_H_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 8 }, /* version */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 6, -1, 7 }, /* sfn */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 8, -2, 6 }, /* riv */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 9, -3, 5 }, /* sub-fn */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 12, -4, 4 }, /* tpc */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 16, -5, 3 }, /* redundancy-Version-Index */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 17, -6, 2 }, /* num-Resource-Blocks */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 18, -7, 1 }, /* starting-Resource-Block */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 21, -8, 0 }, /* harq-id */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 1, 0, 6 }, /* skip0 */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 3, -1, 5 }, /* skip1 */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 5, -2, 4 }, /* skip2 */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 7, -3, 3 }, /* skip3 */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 19, -4, 2 }, /* skip4 */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 20, -5, 1 }, /* skip5 */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 22, -6, 0 }, /* skip6 */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 2, 0, 6 }, /* versions-modulation-type */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 4, -1, 5 }, /* cell-index */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 10, -2, 4 }, /* cqi */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 11, -3, 3 }, /* ul-delay */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 13, -4, 2 }, /* mcs */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 14, -5, 1 }, /* hopping-flag */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 15, -6, 0 } /* transport-Block-Size-Index */
};
static asn_SEQUENCE_specifics_t asn_SPC_LTE_UE_Identification_Message_MSG3_Report_S_H_specs_1 = {
	sizeof(struct LTE_UE_Identification_Message_MSG3_Report_S_H),
	offsetof(struct LTE_UE_Identification_Message_MSG3_Report_S_H, _asn_ctx),
	asn_MAP_LTE_UE_Identification_Message_MSG3_Report_S_H_tag2el_1,
	23,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LTE_UE_Identification_Message_MSG3_Report_S_H = {
	"LTE-UE-Identification-Message-MSG3-Report-S-H",
	"LTE-UE-Identification-Message-MSG3-Report-S-H",
	&asn_OP_SEQUENCE,
	asn_DEF_LTE_UE_Identification_Message_MSG3_Report_S_H_tags_1,
	sizeof(asn_DEF_LTE_UE_Identification_Message_MSG3_Report_S_H_tags_1)
		/sizeof(asn_DEF_LTE_UE_Identification_Message_MSG3_Report_S_H_tags_1[0]), /* 1 */
	asn_DEF_LTE_UE_Identification_Message_MSG3_Report_S_H_tags_1,	/* Same as above */
	sizeof(asn_DEF_LTE_UE_Identification_Message_MSG3_Report_S_H_tags_1)
		/sizeof(asn_DEF_LTE_UE_Identification_Message_MSG3_Report_S_H_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LTE_UE_Identification_Message_MSG3_Report_S_H_1,
	23,	/* Elements count */
	&asn_SPC_LTE_UE_Identification_Message_MSG3_Report_S_H_specs_1	/* Additional specs */
};

