/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Intra-Frequency-Cell-Reselection"
 * 	found in "LTE_ML1_Intra_Frequency_Cell_Reselection.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_10_H_
#define	_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_10_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Idle-Mode-Resel-Meas-Common.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LTE-ML1-Intra-Frequency-Cell-Reselection-pkt-10 */
typedef struct LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_10 {
	Idle_Mode_Resel_Meas_Common_t	 idle_Mode_Resel_Meas_Common;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_10_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_10;

#ifdef __cplusplus
}
#endif

#endif	/* _LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_10_H_ */
#include <asn_internal.h>
