/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-PDCP-UL-Delay-Statistics"
 * 	found in "LTE_PDCP_UL_Delay_Statistics.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_LTE_PDCP_UL_Delay_Statistics_S_HEADER_H_
#define	_LTE_PDCP_UL_Delay_Statistics_S_HEADER_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LTE-PDCP-UL-Delay-Statistics-S-HEADER */
typedef struct LTE_PDCP_UL_Delay_Statistics_S_HEADER {
	long	 version;
	OCTET_STRING_t	 skip0;
	long	 num_rbs;
	long	 num_rst;
	OCTET_STRING_t	 skip1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_PDCP_UL_Delay_Statistics_S_HEADER_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LTE_PDCP_UL_Delay_Statistics_S_HEADER;

#ifdef __cplusplus
}
#endif

#endif	/* _LTE_PDCP_UL_Delay_Statistics_S_HEADER_H_ */
#include <asn_internal.h>
