/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-PDCP-DL-Data-PDU"
 * 	found in "LTE_PDCP_DL_Data_PDU.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_LTE_PDCP_DL_Data_PDU_Pdcp_State_H_
#define	_LTE_PDCP_DL_Data_PDU_Pdcp_State_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LTE-PDCP-DL-Data-PDU-Pdcp-State */
typedef struct LTE_PDCP_DL_Data_PDU_Pdcp_State {
	long	 rb_cfg_index;
	OCTET_STRING_t	 skip1;
	long	 pdcp_sn_length;
	long	 rx_deliv;
	OCTET_STRING_t	 skip2;
	long	 rx_next;
	OCTET_STRING_t	 skip3;
	long	 next_count;
	OCTET_STRING_t	 skip4;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_PDCP_DL_Data_PDU_Pdcp_State_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LTE_PDCP_DL_Data_PDU_Pdcp_State;

#ifdef __cplusplus
}
#endif

#endif	/* _LTE_PDCP_DL_Data_PDU_Pdcp_State_H_ */
#include <asn_internal.h>
