/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Idle-Measurement-Request"
 * 	found in "LTE_ML1_Idle_Measurement_Request.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_H_
#define	_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include "SubPacket-Idle-Meas-Intra-Frequency-Whitelist-Info.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LTE-ML1-Idle-Measurement-Request-Sub-Pkt-7 */
typedef struct LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7 {
	long	 version;
	long	 subpacket_size;
	BIT_STRING_t	 skip14;
	SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info_t	 subPacket_Idle_Meas_Intra_Frequency_Whitelist_Info;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7;

#ifdef __cplusplus
}
#endif

#endif	/* _LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_H_ */
#include <asn_internal.h>
