/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-RRC-Supported-CA-Combos"
 * 	found in "LTE_RRC_Supported_CA_Combos.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_LTE_RRC_Supported_CA_Combos_Bw_Class_H_
#define	_LTE_RRC_Supported_CA_Combos_Bw_Class_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include "Dl-Bw-Class.h"
#include "Dl-Max-Antennas-Index.h"
#include "Ul-Max-Antennas-Index.h"
#include "Ul-Qam-Cap-Index.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LTE-RRC-Supported-CA-Combos-Bw-Class */
typedef struct LTE_RRC_Supported_CA_Combos_Bw_Class {
	long	 band;
	BIT_STRING_t	 skip0;
	Dl_Bw_Class_t	 dl_bw_class;
	BIT_STRING_t	 skip1;
	Dl_Bw_Class_t	 ul_bw_class;
	BIT_STRING_t	 skip2;
	Dl_Max_Antennas_Index_t	 dl_max_antennas_index;
	BIT_STRING_t	 skip3;
	Ul_Max_Antennas_Index_t	 ul_max_antennas_index;
	BIT_STRING_t	 skip4;
	Ul_Qam_Cap_Index_t	 ul_qam_cap_index;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_RRC_Supported_CA_Combos_Bw_Class_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LTE_RRC_Supported_CA_Combos_Bw_Class;

#ifdef __cplusplus
}
#endif

#endif	/* _LTE_RRC_Supported_CA_Combos_Bw_Class_H_ */
#include <asn_internal.h>
