/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-GM-TX-Report"
 * 	found in "LTE_ML1_GM_TX_Report.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_LTE_ML1_GM_TX_Report_R_H_PUCCH_H_
#define	_LTE_ML1_GM_TX_Report_R_H_PUCCH_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <NativeInteger.h>
#include "Scheduling-request-present.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LTE-ML1-GM-TX-Report-R-H-PUCCH */
typedef struct LTE_ML1_GM_TX_Report_R_H_PUCCH {
	BIT_STRING_t	 skip14;
	long	 n_1_pucch;
	long	 beta_pucch;
	Scheduling_request_present_t	 temp_rnti_ack_flag;
	Scheduling_request_present_t	 scheduling_request_present;
	long	 ack_nak_length;
	long	 n_1_pucch_2;
	BIT_STRING_t	 skip7;
	long	 n_1_pucch_1;
	long	 n_1_pucch_0;
	long	 n_1_pucch_num;
	OCTET_STRING_t	 skip8;
	long	 n_1_pucch3;
	BIT_STRING_t	 skip9;
	long	 n_4_pucch;
	long	 n_2_pucch;
	BIT_STRING_t	 skip10;
	long	 n_3_pucch;
	BIT_STRING_t	 skip11;
	long	 n_pucch_4_rb;
	long	 n_5_cdm_idx;
	long	 n_5_pucch;
	BIT_STRING_t	 skip12;
	long	 cc_max_tx_power;
	long	 total_max_tx_power;
	long	 chain0_mtp1;
	long	 chain1_mtp1;
	long	 afc_rx_freq_error;
	OCTET_STRING_t	 skip13;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_ML1_GM_TX_Report_R_H_PUCCH_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LTE_ML1_GM_TX_Report_R_H_PUCCH;

#ifdef __cplusplus
}
#endif

#endif	/* _LTE_ML1_GM_TX_Report_R_H_PUCCH_H_ */
#include <asn_internal.h>
