/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-CA-Metrics-Log-Packet"
 * 	found in "LTE_ML1_CA_Metrics_Log_Packet.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "LTE-ML1-CA-Metrics-Log-Packet-content.h"

static asn_TYPE_member_t asn_MBR_LTE_ML1_CA_Metrics_Log_Packet_content_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_CA_Metrics_Log_Packet_content, pcell_start),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Pcell_start,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pcell-start"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_CA_Metrics_Log_Packet_content, total_metrics),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Total_metrics,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"total-metrics"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_CA_Metrics_Log_Packet_content, ca_configured_metrics),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Total_metrics,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ca-configured-metrics"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_CA_Metrics_Log_Packet_content, ca_activated_metrics),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Total_metrics,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ca-activated-metrics"
		},
};
static const ber_tlv_tag_t asn_DEF_LTE_ML1_CA_Metrics_Log_Packet_content_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LTE_ML1_CA_Metrics_Log_Packet_content_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 3 }, /* pcell-start */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 2 }, /* total-metrics */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -2, 1 }, /* ca-configured-metrics */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -3, 0 } /* ca-activated-metrics */
};
static asn_SEQUENCE_specifics_t asn_SPC_LTE_ML1_CA_Metrics_Log_Packet_content_specs_1 = {
	sizeof(struct LTE_ML1_CA_Metrics_Log_Packet_content),
	offsetof(struct LTE_ML1_CA_Metrics_Log_Packet_content, _asn_ctx),
	asn_MAP_LTE_ML1_CA_Metrics_Log_Packet_content_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LTE_ML1_CA_Metrics_Log_Packet_content = {
	"LTE-ML1-CA-Metrics-Log-Packet-content",
	"LTE-ML1-CA-Metrics-Log-Packet-content",
	&asn_OP_SEQUENCE,
	asn_DEF_LTE_ML1_CA_Metrics_Log_Packet_content_tags_1,
	sizeof(asn_DEF_LTE_ML1_CA_Metrics_Log_Packet_content_tags_1)
		/sizeof(asn_DEF_LTE_ML1_CA_Metrics_Log_Packet_content_tags_1[0]), /* 1 */
	asn_DEF_LTE_ML1_CA_Metrics_Log_Packet_content_tags_1,	/* Same as above */
	sizeof(asn_DEF_LTE_ML1_CA_Metrics_Log_Packet_content_tags_1)
		/sizeof(asn_DEF_LTE_ML1_CA_Metrics_Log_Packet_content_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LTE_ML1_CA_Metrics_Log_Packet_content_1,
	4,	/* Elements count */
	&asn_SPC_LTE_ML1_CA_Metrics_Log_Packet_content_specs_1	/* Additional specs */
};

