/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Intra-Frequency-Cell-Reselection"
 * 	found in "LTE_ML1_Intra_Frequency_Cell_Reselection.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "LTE-ML1-Intra-Frequency-Cell-Reselection-S-H.h"

static int
memb_version_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_number_of_subpackets_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip0_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 2)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_version_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_version_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_number_of_subpackets_constr_3 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_number_of_subpackets_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip0_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	2	/* (SIZE(2..2)) */};
static asn_per_constraints_t asn_PER_memb_skip0_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  2,  2 }	/* (SIZE(2..2)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_LTE_ML1_Intra_Frequency_Cell_Reselection_S_H_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Intra_Frequency_Cell_Reselection_S_H, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_version_constr_2, &asn_PER_memb_version_constr_2,  memb_version_constraint_1 },
		0, 0, /* No default value */
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Intra_Frequency_Cell_Reselection_S_H, number_of_subpackets),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_number_of_subpackets_constr_3, &asn_PER_memb_number_of_subpackets_constr_3,  memb_number_of_subpackets_constraint_1 },
		0, 0, /* No default value */
		"number-of-subpackets"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Intra_Frequency_Cell_Reselection_S_H, skip0),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_skip0_constr_4, &asn_PER_memb_skip0_constr_4,  memb_skip0_constraint_1 },
		0, 0, /* No default value */
		"skip0"
		},
};
static const ber_tlv_tag_t asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_S_H_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LTE_ML1_Intra_Frequency_Cell_Reselection_S_H_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* version */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 }, /* number-of-subpackets */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, 0, 0 } /* skip0 */
};
static asn_SEQUENCE_specifics_t asn_SPC_LTE_ML1_Intra_Frequency_Cell_Reselection_S_H_specs_1 = {
	sizeof(struct LTE_ML1_Intra_Frequency_Cell_Reselection_S_H),
	offsetof(struct LTE_ML1_Intra_Frequency_Cell_Reselection_S_H, _asn_ctx),
	asn_MAP_LTE_ML1_Intra_Frequency_Cell_Reselection_S_H_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_S_H = {
	"LTE-ML1-Intra-Frequency-Cell-Reselection-S-H",
	"LTE-ML1-Intra-Frequency-Cell-Reselection-S-H",
	&asn_OP_SEQUENCE,
	asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_S_H_tags_1,
	sizeof(asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_S_H_tags_1)
		/sizeof(asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_S_H_tags_1[0]), /* 1 */
	asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_S_H_tags_1,	/* Same as above */
	sizeof(asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_S_H_tags_1)
		/sizeof(asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_S_H_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LTE_ML1_Intra_Frequency_Cell_Reselection_S_H_1,
	3,	/* Elements count */
	&asn_SPC_LTE_ML1_Intra_Frequency_Cell_Reselection_S_H_specs_1	/* Additional specs */
};

