/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-Contention-Resolution-Message-MSG4-Report"
 * 	found in "LTE_Contention_Resolution_Message_MSG4_Report.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_LTE_Contention_Resolution_Message_MSG4_Report_S_H_H_
#define	_LTE_Contention_Resolution_Message_MSG4_Report_S_H_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include "Contention-Result.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LTE-Contention-Resolution-Message-MSG4-Report-S-H */
typedef struct LTE_Contention_Resolution_Message_MSG4_Report_S_H {
	long	 version;
	BIT_STRING_t	 skip0;
	BIT_STRING_t	 skip1;
	long	 uL_ACK_Timing_Sub_fn;
	long	 uL_ACK_Timing_SFN;
	Contention_Result_t	 contention_Result;
	long	 sub_fn;
	long	 versions_sfn;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_Contention_Resolution_Message_MSG4_Report_S_H_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LTE_Contention_Resolution_Message_MSG4_Report_S_H;

#ifdef __cplusplus
}
#endif

#endif	/* _LTE_Contention_Resolution_Message_MSG4_Report_S_H_H_ */
#include <asn_internal.h>
