/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-PDCP-UL-Delay-Statistics"
 * 	found in "LTE_PDCP_UL_Delay_Statistics.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "LTE-PDCP-UL-Delay-Statistics-RBs.h"

static int
memb_rb_cfg_id_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_discard_timer_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip2_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_rb_cfg_id_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_rb_cfg_id_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_discard_timer_constr_3 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65535) */,
	-1};
static asn_per_constraints_t asn_PER_memb_discard_timer_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip2_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	1	/* (SIZE(1..1)) */};
static asn_per_constraints_t asn_PER_memb_skip2_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  1,  1 }	/* (SIZE(1..1)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_LTE_PDCP_UL_Delay_Statistics_RBs_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_UL_Delay_Statistics_RBs, rb_cfg_id),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_rb_cfg_id_constr_2, &asn_PER_memb_rb_cfg_id_constr_2,  memb_rb_cfg_id_constraint_1 },
		0, 0, /* No default value */
		"rb-cfg-id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_UL_Delay_Statistics_RBs, discard_timer),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_discard_timer_constr_3, &asn_PER_memb_discard_timer_constr_3,  memb_discard_timer_constraint_1 },
		0, 0, /* No default value */
		"discard-timer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_UL_Delay_Statistics_RBs, skip2),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_skip2_constr_4, &asn_PER_memb_skip2_constr_4,  memb_skip2_constraint_1 },
		0, 0, /* No default value */
		"skip2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_PDCP_UL_Delay_Statistics_RBs, total),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Total,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"total"
		},
};
static const ber_tlv_tag_t asn_DEF_LTE_PDCP_UL_Delay_Statistics_RBs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LTE_PDCP_UL_Delay_Statistics_RBs_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* rb-cfg-id */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 }, /* discard-timer */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, 0, 0 }, /* skip2 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, 0, 0 } /* total */
};
static asn_SEQUENCE_specifics_t asn_SPC_LTE_PDCP_UL_Delay_Statistics_RBs_specs_1 = {
	sizeof(struct LTE_PDCP_UL_Delay_Statistics_RBs),
	offsetof(struct LTE_PDCP_UL_Delay_Statistics_RBs, _asn_ctx),
	asn_MAP_LTE_PDCP_UL_Delay_Statistics_RBs_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LTE_PDCP_UL_Delay_Statistics_RBs = {
	"LTE-PDCP-UL-Delay-Statistics-RBs",
	"LTE-PDCP-UL-Delay-Statistics-RBs",
	&asn_OP_SEQUENCE,
	asn_DEF_LTE_PDCP_UL_Delay_Statistics_RBs_tags_1,
	sizeof(asn_DEF_LTE_PDCP_UL_Delay_Statistics_RBs_tags_1)
		/sizeof(asn_DEF_LTE_PDCP_UL_Delay_Statistics_RBs_tags_1[0]), /* 1 */
	asn_DEF_LTE_PDCP_UL_Delay_Statistics_RBs_tags_1,	/* Same as above */
	sizeof(asn_DEF_LTE_PDCP_UL_Delay_Statistics_RBs_tags_1)
		/sizeof(asn_DEF_LTE_PDCP_UL_Delay_Statistics_RBs_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LTE_PDCP_UL_Delay_Statistics_RBs_1,
	4,	/* Elements count */
	&asn_SPC_LTE_PDCP_UL_Delay_Statistics_RBs_specs_1	/* Additional specs */
};

