/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-GM-TX-Report"
 * 	found in "LTE_ML1_GM_TX_Report.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "LTE-ML1-GM-TX-Report-R-H-Exd.h"

static int
memb_skip5_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 2)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_total_tx_power_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_w_ul_dai_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip6_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 4)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_skip5_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	2	/* (SIZE(2..2)) */};
static asn_per_constraints_t asn_PER_memb_skip5_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  2,  2 }	/* (SIZE(2..2)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_total_tx_power_constr_3 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_total_tx_power_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_w_ul_dai_constr_5 CC_NOTUSED = {
	{ 1, 1 }	/* (0..1) */,
	-1};
static asn_per_constraints_t asn_PER_memb_w_ul_dai_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip6_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	4	/* (SIZE(4..4)) */};
static asn_per_constraints_t asn_PER_memb_skip6_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  4,  4 }	/* (SIZE(4..4)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_LTE_ML1_GM_TX_Report_R_H_Exd_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_GM_TX_Report_R_H_Exd, skip5),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip5_constr_2, &asn_PER_memb_skip5_constr_2,  memb_skip5_constraint_1 },
		0, 0, /* No default value */
		"skip5"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_GM_TX_Report_R_H_Exd, total_tx_power),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_total_tx_power_constr_3, &asn_PER_memb_total_tx_power_constr_3,  memb_total_tx_power_constraint_1 },
		0, 0, /* No default value */
		"total-tx-power"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_GM_TX_Report_R_H_Exd, eca_ack_reporting_mode),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_Eca_ack_reporting_mode,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eca-ack-reporting-mode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_GM_TX_Report_R_H_Exd, w_ul_dai),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_w_ul_dai_constr_5, &asn_PER_memb_w_ul_dai_constr_5,  memb_w_ul_dai_constraint_1 },
		0, 0, /* No default value */
		"w-ul-dai"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_GM_TX_Report_R_H_Exd, skip6),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip6_constr_6, &asn_PER_memb_skip6_constr_6,  memb_skip6_constraint_1 },
		0, 0, /* No default value */
		"skip6"
		},
};
static const ber_tlv_tag_t asn_DEF_LTE_ML1_GM_TX_Report_R_H_Exd_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LTE_ML1_GM_TX_Report_R_H_Exd_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 1 }, /* total-tx-power */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, -1, 0 }, /* w-ul-dai */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 0, 0, 1 }, /* skip5 */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 4, -1, 0 }, /* skip6 */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 2, 0, 0 } /* eca-ack-reporting-mode */
};
static asn_SEQUENCE_specifics_t asn_SPC_LTE_ML1_GM_TX_Report_R_H_Exd_specs_1 = {
	sizeof(struct LTE_ML1_GM_TX_Report_R_H_Exd),
	offsetof(struct LTE_ML1_GM_TX_Report_R_H_Exd, _asn_ctx),
	asn_MAP_LTE_ML1_GM_TX_Report_R_H_Exd_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LTE_ML1_GM_TX_Report_R_H_Exd = {
	"LTE-ML1-GM-TX-Report-R-H-Exd",
	"LTE-ML1-GM-TX-Report-R-H-Exd",
	&asn_OP_SEQUENCE,
	asn_DEF_LTE_ML1_GM_TX_Report_R_H_Exd_tags_1,
	sizeof(asn_DEF_LTE_ML1_GM_TX_Report_R_H_Exd_tags_1)
		/sizeof(asn_DEF_LTE_ML1_GM_TX_Report_R_H_Exd_tags_1[0]), /* 1 */
	asn_DEF_LTE_ML1_GM_TX_Report_R_H_Exd_tags_1,	/* Same as above */
	sizeof(asn_DEF_LTE_ML1_GM_TX_Report_R_H_Exd_tags_1)
		/sizeof(asn_DEF_LTE_ML1_GM_TX_Report_R_H_Exd_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LTE_ML1_GM_TX_Report_R_H_Exd_1,
	5,	/* Elements count */
	&asn_SPC_LTE_ML1_GM_TX_Report_R_H_Exd_specs_1	/* Additional specs */
};

