/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Common-DC-Offset"
 * 	found in "LTE_ML1_Common _DC_Offset.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "LTE-ML1-Common-DC-Offset-S-H.h"

static int
e_arfcn_8_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
memb_version_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip0_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 7)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_band_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip1_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 4)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_e_arfcn_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static asn_oer_constraints_t asn_OER_type_e_arfcn_constr_8 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_e_arfcn_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_version_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_version_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip0_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	7	/* (SIZE(7..7)) */};
static asn_per_constraints_t asn_PER_memb_skip0_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  7,  7 }	/* (SIZE(7..7)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_band_constr_5 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_band_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip1_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	4	/* (SIZE(4..4)) */};
static asn_per_constraints_t asn_PER_memb_skip1_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  4,  4 }	/* (SIZE(4..4)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_e_arfcn_constr_8 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_e_arfcn_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_specifics_t asn_SPC_e_arfcn_specs_8 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_e_arfcn_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_e_arfcn_8 = {
	"e-arfcn",
	"e-arfcn",
	&asn_OP_NativeInteger,
	asn_DEF_e_arfcn_tags_8,
	sizeof(asn_DEF_e_arfcn_tags_8)
		/sizeof(asn_DEF_e_arfcn_tags_8[0]), /* 1 */
	asn_DEF_e_arfcn_tags_8,	/* Same as above */
	sizeof(asn_DEF_e_arfcn_tags_8)
		/sizeof(asn_DEF_e_arfcn_tags_8[0]), /* 1 */
	{ &asn_OER_type_e_arfcn_constr_8, &asn_PER_type_e_arfcn_constr_8, e_arfcn_8_constraint },
	0, 0,	/* No members */
	&asn_SPC_e_arfcn_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_LTE_ML1_Common_DC_Offset_S_H_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Common_DC_Offset_S_H, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_version_constr_2, &asn_PER_memb_version_constr_2,  memb_version_constraint_1 },
		0, 0, /* No default value */
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Common_DC_Offset_S_H, skip0),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip0_constr_3, &asn_PER_memb_skip0_constr_3,  memb_skip0_constraint_1 },
		0, 0, /* No default value */
		"skip0"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Common_DC_Offset_S_H, update),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_Update,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"update"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Common_DC_Offset_S_H, band),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_band_constr_5, &asn_PER_memb_band_constr_5,  memb_band_constraint_1 },
		0, 0, /* No default value */
		"band"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Common_DC_Offset_S_H, skip1),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip1_constr_6, &asn_PER_memb_skip1_constr_6,  memb_skip1_constraint_1 },
		0, 0, /* No default value */
		"skip1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Common_DC_Offset_S_H, bandwidth_index),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_Bandwidth_index,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"bandwidth-index"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LTE_ML1_Common_DC_Offset_S_H, e_arfcn),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_e_arfcn_8,
		0,
		{ &asn_OER_memb_e_arfcn_constr_8, &asn_PER_memb_e_arfcn_constr_8,  memb_e_arfcn_constraint_1 },
		0, 0, /* No default value */
		"e-arfcn"
		},
};
static const ber_tlv_tag_t asn_DEF_LTE_ML1_Common_DC_Offset_S_H_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LTE_ML1_Common_DC_Offset_S_H_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 2 }, /* version */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, -1, 1 }, /* band */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 6, -2, 0 }, /* e-arfcn */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 1, 0, 1 }, /* skip0 */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 4, -1, 0 }, /* skip1 */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 2, 0, 1 }, /* update */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 5, -1, 0 } /* bandwidth-index */
};
static asn_SEQUENCE_specifics_t asn_SPC_LTE_ML1_Common_DC_Offset_S_H_specs_1 = {
	sizeof(struct LTE_ML1_Common_DC_Offset_S_H),
	offsetof(struct LTE_ML1_Common_DC_Offset_S_H, _asn_ctx),
	asn_MAP_LTE_ML1_Common_DC_Offset_S_H_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LTE_ML1_Common_DC_Offset_S_H = {
	"LTE-ML1-Common-DC-Offset-S-H",
	"LTE-ML1-Common-DC-Offset-S-H",
	&asn_OP_SEQUENCE,
	asn_DEF_LTE_ML1_Common_DC_Offset_S_H_tags_1,
	sizeof(asn_DEF_LTE_ML1_Common_DC_Offset_S_H_tags_1)
		/sizeof(asn_DEF_LTE_ML1_Common_DC_Offset_S_H_tags_1[0]), /* 1 */
	asn_DEF_LTE_ML1_Common_DC_Offset_S_H_tags_1,	/* Same as above */
	sizeof(asn_DEF_LTE_ML1_Common_DC_Offset_S_H_tags_1)
		/sizeof(asn_DEF_LTE_ML1_Common_DC_Offset_S_H_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LTE_ML1_Common_DC_Offset_S_H_1,
	7,	/* Elements count */
	&asn_SPC_LTE_ML1_Common_DC_Offset_S_H_specs_1	/* Additional specs */
};

