/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-S-Criteria-Check-Procedure"
 * 	found in "LTE_ML1_S_Criteria_Check_Procedure.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_LTE_ML1_S_Criteria_Check_Procedure_Subpacket_ID_9_H_
#define	_LTE_ML1_S_Criteria_Check_Procedure_Subpacket_ID_9_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "SubPacket-Idle-Meas-Serving-Cell-Measurements.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LTE-ML1-S-Criteria-Check-Procedure-Subpacket-ID-9 */
typedef struct LTE_ML1_S_Criteria_Check_Procedure_Subpacket_ID_9 {
	long	 version;
	long	 subpacket_size;
	SubPacket_Idle_Meas_Serving_Cell_Measurements_t	 subPacket_Idle_Meas_Serving_Cell_Measurements;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_ML1_S_Criteria_Check_Procedure_Subpacket_ID_9_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LTE_ML1_S_Criteria_Check_Procedure_Subpacket_ID_9;

#ifdef __cplusplus
}
#endif

#endif	/* _LTE_ML1_S_Criteria_Check_Procedure_Subpacket_ID_9_H_ */
#include <asn_internal.h>
