/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-UE-Identification-Message-MSG3-Report"
 * 	found in "LTE_UE_Identification_Message_MSG3_Report.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Mcs_H_
#define	_Mcs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Mcs {
	Mcs_mcs_2	= 0,
	Mcs_unkown1	= 1,
	Mcs_unkown2	= 2,
	Mcs_unkown3	= 3,
	Mcs_unkown4	= 4
} e_Mcs;

/* Mcs */
typedef long	 Mcs_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Mcs_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Mcs;
extern const asn_INTEGER_specifics_t asn_SPC_Mcs_specs_1;
asn_struct_free_f Mcs_free;
asn_struct_print_f Mcs_print;
asn_constr_check_f Mcs_constraint;
ber_type_decoder_f Mcs_decode_ber;
der_type_encoder_f Mcs_encode_der;
xer_type_decoder_f Mcs_decode_xer;
xer_type_encoder_f Mcs_encode_xer;
oer_type_decoder_f Mcs_decode_oer;
oer_type_encoder_f Mcs_encode_oer;
per_type_decoder_f Mcs_decode_uper;
per_type_encoder_f Mcs_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Mcs_H_ */
#include <asn_internal.h>
