/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-LL1-Serving-Cell-Measurement-Results"
 * 	found in "LTE_LL1_Serving_Cell_Measurement_Results.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Measurement_BW_H_
#define	_Measurement_BW_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Measurement_BW {
	Measurement_BW_unknown0	= 0,
	Measurement_BW_unknown1	= 1,
	Measurement_BW_unknown2	= 2,
	Measurement_BW_unknown3	= 3,
	Measurement_BW_unknown4	= 4,
	Measurement_BW_unknown5	= 5,
	Measurement_BW_bw_10_MHz	= 6,
	Measurement_BW_unknown7	= 7,
	Measurement_BW_bw_15_MHz	= 8
} e_Measurement_BW;

/* Measurement-BW */
typedef long	 Measurement_BW_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Measurement_BW_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Measurement_BW;
extern const asn_INTEGER_specifics_t asn_SPC_Measurement_BW_specs_1;
asn_struct_free_f Measurement_BW_free;
asn_struct_print_f Measurement_BW_print;
asn_constr_check_f Measurement_BW_constraint;
ber_type_decoder_f Measurement_BW_decode_ber;
der_type_encoder_f Measurement_BW_encode_der;
xer_type_decoder_f Measurement_BW_decode_xer;
xer_type_encoder_f Measurement_BW_encode_xer;
oer_type_decoder_f Measurement_BW_decode_oer;
oer_type_encoder_f Measurement_BW_encode_oer;
per_type_decoder_f Measurement_BW_decode_uper;
per_type_encoder_f Measurement_BW_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Measurement_BW_H_ */
#include <asn_internal.h>
