/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Serving-Cell-Measurements-And-Evaluation"
 * 	found in "LTE_ML1_Serving_Cell_Measurements_And_Evaluation.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Measurement_rules_H_
#define	_Measurement_rules_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Measurement_rules {
	Measurement_rules_unknown0	= 0,
	Measurement_rules_unknown1	= 1,
	Measurement_rules_unknown2	= 2,
	Measurement_rules_unknown3	= 3,
	Measurement_rules_unknown4	= 4,
	Measurement_rules_unknown5	= 5,
	Measurement_rules_unknown6	= 6,
	Measurement_rules_unknown7	= 7,
	Measurement_rules_unknown8	= 8,
	Measurement_rules_unknown9	= 9
} e_Measurement_rules;

/* Measurement-rules */
typedef long	 Measurement_rules_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Measurement_rules_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Measurement_rules;
extern const asn_INTEGER_specifics_t asn_SPC_Measurement_rules_specs_1;
asn_struct_free_f Measurement_rules_free;
asn_struct_print_f Measurement_rules_print;
asn_constr_check_f Measurement_rules_constraint;
ber_type_decoder_f Measurement_rules_decode_ber;
der_type_encoder_f Measurement_rules_encode_der;
xer_type_decoder_f Measurement_rules_decode_xer;
xer_type_encoder_f Measurement_rules_encode_xer;
oer_type_decoder_f Measurement_rules_decode_oer;
oer_type_encoder_f Measurement_rules_encode_oer;
per_type_decoder_f Measurement_rules_decode_uper;
per_type_encoder_f Measurement_rules_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Measurement_rules_H_ */
#include <asn_internal.h>
