/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MetadataHeader"
 * 	found in "Metadata_Header.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_MetadataHeader_H_
#define	_MetadataHeader_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MetadataHeader */
typedef struct MetadataHeader {
	long	 msg_len;
	OCTET_STRING_t	 logcode;
	OCTET_STRING_t	 timestamp;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MetadataHeader_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MetadataHeader;

#ifdef __cplusplus
}
#endif

#endif	/* _MetadataHeader_H_ */
#include <asn_internal.h>
