/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DCIReportModule"
 * 	found in "LTE_ML1_DCI_Information_Report.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_NumInfoMetaHeaderStructure_H_
#define	_NumInfoMetaHeaderStructure_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DuplexMode.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NumInfoMetaHeaderStructure */
typedef struct NumInfoMetaHeaderStructure {
	DuplexMode_t	 duplexmode;
	long	 skip1;
	long	 numofrecords;
	long	 subframecfg;
	long	 skip2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NumInfoMetaHeaderStructure_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NumInfoMetaHeaderStructure;
extern asn_SEQUENCE_specifics_t asn_SPC_NumInfoMetaHeaderStructure_specs_1;
extern asn_TYPE_member_t asn_MBR_NumInfoMetaHeaderStructure_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _NumInfoMetaHeaderStructure_H_ */
#include <asn_internal.h>
