/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-PDCP-UL-Delay-Statistics"
 * 	found in "LTE_PDCP_UL_Delay_Statistics.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "Pdcp-delay-pkt-count2.h"

static int
data_80_88_2_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
data_88_96_3_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
data_96_104_4_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
data_104_112_5_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
data_112_120_6_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
data_120_128_7_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
data_128_136_8_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
data_136_144_9_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
data_144_152_10_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
data_152_160_11_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
memb_data_80_88_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_data_88_96_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_data_96_104_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_data_104_112_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_data_112_120_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_data_120_128_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_data_128_136_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_data_136_144_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_data_144_152_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_data_152_160_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static asn_oer_constraints_t asn_OER_type_data_80_88_constr_2 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_80_88_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_data_88_96_constr_3 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_88_96_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_data_96_104_constr_4 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_96_104_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_data_104_112_constr_5 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_104_112_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_data_112_120_constr_6 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_112_120_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_data_120_128_constr_7 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_120_128_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_data_128_136_constr_8 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_128_136_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_data_136_144_constr_9 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_136_144_constr_9 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_data_144_152_constr_10 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_144_152_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_data_152_160_constr_11 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_152_160_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_80_88_constr_2 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_80_88_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_88_96_constr_3 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_88_96_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_96_104_constr_4 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_96_104_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_104_112_constr_5 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_104_112_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_112_120_constr_6 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_112_120_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_120_128_constr_7 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_120_128_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_128_136_constr_8 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_128_136_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_136_144_constr_9 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_136_144_constr_9 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_144_152_constr_10 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_144_152_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_152_160_constr_11 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_152_160_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_specifics_t asn_SPC_data_80_88_specs_2 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_80_88_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_80_88_2 = {
	"data-80-88",
	"data-80-88",
	&asn_OP_NativeInteger,
	asn_DEF_data_80_88_tags_2,
	sizeof(asn_DEF_data_80_88_tags_2)
		/sizeof(asn_DEF_data_80_88_tags_2[0]), /* 1 */
	asn_DEF_data_80_88_tags_2,	/* Same as above */
	sizeof(asn_DEF_data_80_88_tags_2)
		/sizeof(asn_DEF_data_80_88_tags_2[0]), /* 1 */
	{ &asn_OER_type_data_80_88_constr_2, &asn_PER_type_data_80_88_constr_2, data_80_88_2_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_80_88_specs_2	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_data_88_96_specs_3 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_88_96_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_88_96_3 = {
	"data-88-96",
	"data-88-96",
	&asn_OP_NativeInteger,
	asn_DEF_data_88_96_tags_3,
	sizeof(asn_DEF_data_88_96_tags_3)
		/sizeof(asn_DEF_data_88_96_tags_3[0]), /* 1 */
	asn_DEF_data_88_96_tags_3,	/* Same as above */
	sizeof(asn_DEF_data_88_96_tags_3)
		/sizeof(asn_DEF_data_88_96_tags_3[0]), /* 1 */
	{ &asn_OER_type_data_88_96_constr_3, &asn_PER_type_data_88_96_constr_3, data_88_96_3_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_88_96_specs_3	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_data_96_104_specs_4 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_96_104_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_96_104_4 = {
	"data-96-104",
	"data-96-104",
	&asn_OP_NativeInteger,
	asn_DEF_data_96_104_tags_4,
	sizeof(asn_DEF_data_96_104_tags_4)
		/sizeof(asn_DEF_data_96_104_tags_4[0]), /* 1 */
	asn_DEF_data_96_104_tags_4,	/* Same as above */
	sizeof(asn_DEF_data_96_104_tags_4)
		/sizeof(asn_DEF_data_96_104_tags_4[0]), /* 1 */
	{ &asn_OER_type_data_96_104_constr_4, &asn_PER_type_data_96_104_constr_4, data_96_104_4_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_96_104_specs_4	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_data_104_112_specs_5 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_104_112_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_104_112_5 = {
	"data-104-112",
	"data-104-112",
	&asn_OP_NativeInteger,
	asn_DEF_data_104_112_tags_5,
	sizeof(asn_DEF_data_104_112_tags_5)
		/sizeof(asn_DEF_data_104_112_tags_5[0]), /* 1 */
	asn_DEF_data_104_112_tags_5,	/* Same as above */
	sizeof(asn_DEF_data_104_112_tags_5)
		/sizeof(asn_DEF_data_104_112_tags_5[0]), /* 1 */
	{ &asn_OER_type_data_104_112_constr_5, &asn_PER_type_data_104_112_constr_5, data_104_112_5_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_104_112_specs_5	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_data_112_120_specs_6 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_112_120_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_112_120_6 = {
	"data-112-120",
	"data-112-120",
	&asn_OP_NativeInteger,
	asn_DEF_data_112_120_tags_6,
	sizeof(asn_DEF_data_112_120_tags_6)
		/sizeof(asn_DEF_data_112_120_tags_6[0]), /* 1 */
	asn_DEF_data_112_120_tags_6,	/* Same as above */
	sizeof(asn_DEF_data_112_120_tags_6)
		/sizeof(asn_DEF_data_112_120_tags_6[0]), /* 1 */
	{ &asn_OER_type_data_112_120_constr_6, &asn_PER_type_data_112_120_constr_6, data_112_120_6_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_112_120_specs_6	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_data_120_128_specs_7 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_120_128_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_120_128_7 = {
	"data-120-128",
	"data-120-128",
	&asn_OP_NativeInteger,
	asn_DEF_data_120_128_tags_7,
	sizeof(asn_DEF_data_120_128_tags_7)
		/sizeof(asn_DEF_data_120_128_tags_7[0]), /* 1 */
	asn_DEF_data_120_128_tags_7,	/* Same as above */
	sizeof(asn_DEF_data_120_128_tags_7)
		/sizeof(asn_DEF_data_120_128_tags_7[0]), /* 1 */
	{ &asn_OER_type_data_120_128_constr_7, &asn_PER_type_data_120_128_constr_7, data_120_128_7_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_120_128_specs_7	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_data_128_136_specs_8 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_128_136_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_128_136_8 = {
	"data-128-136",
	"data-128-136",
	&asn_OP_NativeInteger,
	asn_DEF_data_128_136_tags_8,
	sizeof(asn_DEF_data_128_136_tags_8)
		/sizeof(asn_DEF_data_128_136_tags_8[0]), /* 1 */
	asn_DEF_data_128_136_tags_8,	/* Same as above */
	sizeof(asn_DEF_data_128_136_tags_8)
		/sizeof(asn_DEF_data_128_136_tags_8[0]), /* 1 */
	{ &asn_OER_type_data_128_136_constr_8, &asn_PER_type_data_128_136_constr_8, data_128_136_8_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_128_136_specs_8	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_data_136_144_specs_9 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_136_144_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_136_144_9 = {
	"data-136-144",
	"data-136-144",
	&asn_OP_NativeInteger,
	asn_DEF_data_136_144_tags_9,
	sizeof(asn_DEF_data_136_144_tags_9)
		/sizeof(asn_DEF_data_136_144_tags_9[0]), /* 1 */
	asn_DEF_data_136_144_tags_9,	/* Same as above */
	sizeof(asn_DEF_data_136_144_tags_9)
		/sizeof(asn_DEF_data_136_144_tags_9[0]), /* 1 */
	{ &asn_OER_type_data_136_144_constr_9, &asn_PER_type_data_136_144_constr_9, data_136_144_9_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_136_144_specs_9	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_data_144_152_specs_10 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_144_152_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_144_152_10 = {
	"data-144-152",
	"data-144-152",
	&asn_OP_NativeInteger,
	asn_DEF_data_144_152_tags_10,
	sizeof(asn_DEF_data_144_152_tags_10)
		/sizeof(asn_DEF_data_144_152_tags_10[0]), /* 1 */
	asn_DEF_data_144_152_tags_10,	/* Same as above */
	sizeof(asn_DEF_data_144_152_tags_10)
		/sizeof(asn_DEF_data_144_152_tags_10[0]), /* 1 */
	{ &asn_OER_type_data_144_152_constr_10, &asn_PER_type_data_144_152_constr_10, data_144_152_10_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_144_152_specs_10	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_data_152_160_specs_11 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_152_160_tags_11[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_152_160_11 = {
	"data-152-160",
	"data-152-160",
	&asn_OP_NativeInteger,
	asn_DEF_data_152_160_tags_11,
	sizeof(asn_DEF_data_152_160_tags_11)
		/sizeof(asn_DEF_data_152_160_tags_11[0]), /* 1 */
	asn_DEF_data_152_160_tags_11,	/* Same as above */
	sizeof(asn_DEF_data_152_160_tags_11)
		/sizeof(asn_DEF_data_152_160_tags_11[0]), /* 1 */
	{ &asn_OER_type_data_152_160_constr_11, &asn_PER_type_data_152_160_constr_11, data_152_160_11_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_152_160_specs_11	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Pdcp_delay_pkt_count2_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count2, data_80_88),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_80_88_2,
		0,
		{ &asn_OER_memb_data_80_88_constr_2, &asn_PER_memb_data_80_88_constr_2,  memb_data_80_88_constraint_1 },
		0, 0, /* No default value */
		"data-80-88"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count2, data_88_96),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_88_96_3,
		0,
		{ &asn_OER_memb_data_88_96_constr_3, &asn_PER_memb_data_88_96_constr_3,  memb_data_88_96_constraint_1 },
		0, 0, /* No default value */
		"data-88-96"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count2, data_96_104),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_96_104_4,
		0,
		{ &asn_OER_memb_data_96_104_constr_4, &asn_PER_memb_data_96_104_constr_4,  memb_data_96_104_constraint_1 },
		0, 0, /* No default value */
		"data-96-104"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count2, data_104_112),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_104_112_5,
		0,
		{ &asn_OER_memb_data_104_112_constr_5, &asn_PER_memb_data_104_112_constr_5,  memb_data_104_112_constraint_1 },
		0, 0, /* No default value */
		"data-104-112"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count2, data_112_120),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_112_120_6,
		0,
		{ &asn_OER_memb_data_112_120_constr_6, &asn_PER_memb_data_112_120_constr_6,  memb_data_112_120_constraint_1 },
		0, 0, /* No default value */
		"data-112-120"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count2, data_120_128),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_120_128_7,
		0,
		{ &asn_OER_memb_data_120_128_constr_7, &asn_PER_memb_data_120_128_constr_7,  memb_data_120_128_constraint_1 },
		0, 0, /* No default value */
		"data-120-128"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count2, data_128_136),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_128_136_8,
		0,
		{ &asn_OER_memb_data_128_136_constr_8, &asn_PER_memb_data_128_136_constr_8,  memb_data_128_136_constraint_1 },
		0, 0, /* No default value */
		"data-128-136"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count2, data_136_144),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_136_144_9,
		0,
		{ &asn_OER_memb_data_136_144_constr_9, &asn_PER_memb_data_136_144_constr_9,  memb_data_136_144_constraint_1 },
		0, 0, /* No default value */
		"data-136-144"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count2, data_144_152),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_144_152_10,
		0,
		{ &asn_OER_memb_data_144_152_constr_10, &asn_PER_memb_data_144_152_constr_10,  memb_data_144_152_constraint_1 },
		0, 0, /* No default value */
		"data-144-152"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count2, data_152_160),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_152_160_11,
		0,
		{ &asn_OER_memb_data_152_160_constr_11, &asn_PER_memb_data_152_160_constr_11,  memb_data_152_160_constraint_1 },
		0, 0, /* No default value */
		"data-152-160"
		},
};
static const ber_tlv_tag_t asn_DEF_Pdcp_delay_pkt_count2_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Pdcp_delay_pkt_count2_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 9 }, /* data-80-88 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 8 }, /* data-88-96 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -2, 7 }, /* data-96-104 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, -3, 6 }, /* data-104-112 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, -4, 5 }, /* data-112-120 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 5, -5, 4 }, /* data-120-128 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 6, -6, 3 }, /* data-128-136 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 7, -7, 2 }, /* data-136-144 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 8, -8, 1 }, /* data-144-152 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 9, -9, 0 } /* data-152-160 */
};
asn_SEQUENCE_specifics_t asn_SPC_Pdcp_delay_pkt_count2_specs_1 = {
	sizeof(struct Pdcp_delay_pkt_count2),
	offsetof(struct Pdcp_delay_pkt_count2, _asn_ctx),
	asn_MAP_Pdcp_delay_pkt_count2_tag2el_1,
	10,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Pdcp_delay_pkt_count2 = {
	"Pdcp-delay-pkt-count2",
	"Pdcp-delay-pkt-count2",
	&asn_OP_SEQUENCE,
	asn_DEF_Pdcp_delay_pkt_count2_tags_1,
	sizeof(asn_DEF_Pdcp_delay_pkt_count2_tags_1)
		/sizeof(asn_DEF_Pdcp_delay_pkt_count2_tags_1[0]), /* 1 */
	asn_DEF_Pdcp_delay_pkt_count2_tags_1,	/* Same as above */
	sizeof(asn_DEF_Pdcp_delay_pkt_count2_tags_1)
		/sizeof(asn_DEF_Pdcp_delay_pkt_count2_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Pdcp_delay_pkt_count2_1,
	10,	/* Elements count */
	&asn_SPC_Pdcp_delay_pkt_count2_specs_1	/* Additional specs */
};

