/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-PDCP-UL-Delay-Statistics"
 * 	found in "LTE_PDCP_UL_Delay_Statistics.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "Pdcp-delay-pkt-count3.h"

static int
data_160_168_2_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
data_168_176_3_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
data_176_184_4_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
data_184_192_5_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
data_192_200_6_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
data_200_208_7_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
data_208_216_8_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
data_216_224_9_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
data_224_232_10_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
data_232_240_11_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
data_240_12_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
memb_data_160_168_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_data_168_176_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_data_176_184_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_data_184_192_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_data_192_200_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_data_200_208_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_data_208_216_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_data_216_224_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_data_224_232_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_data_232_240_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_data_240_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static asn_oer_constraints_t asn_OER_type_data_160_168_constr_2 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_160_168_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_data_168_176_constr_3 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_168_176_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_data_176_184_constr_4 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_176_184_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_data_184_192_constr_5 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_184_192_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_data_192_200_constr_6 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_192_200_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_data_200_208_constr_7 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_200_208_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_data_208_216_constr_8 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_208_216_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_data_216_224_constr_9 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_216_224_constr_9 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_data_224_232_constr_10 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_224_232_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_data_232_240_constr_11 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_232_240_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_data_240_constr_12 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_data_240_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_160_168_constr_2 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_160_168_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_168_176_constr_3 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_168_176_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_176_184_constr_4 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_176_184_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_184_192_constr_5 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_184_192_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_192_200_constr_6 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_192_200_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_200_208_constr_7 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_200_208_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_208_216_constr_8 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_208_216_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_216_224_constr_9 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_216_224_constr_9 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_224_232_constr_10 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_224_232_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_232_240_constr_11 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_232_240_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_data_240_constr_12 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_data_240_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_specifics_t asn_SPC_data_160_168_specs_2 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_160_168_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_160_168_2 = {
	"data-160-168",
	"data-160-168",
	&asn_OP_NativeInteger,
	asn_DEF_data_160_168_tags_2,
	sizeof(asn_DEF_data_160_168_tags_2)
		/sizeof(asn_DEF_data_160_168_tags_2[0]), /* 1 */
	asn_DEF_data_160_168_tags_2,	/* Same as above */
	sizeof(asn_DEF_data_160_168_tags_2)
		/sizeof(asn_DEF_data_160_168_tags_2[0]), /* 1 */
	{ &asn_OER_type_data_160_168_constr_2, &asn_PER_type_data_160_168_constr_2, data_160_168_2_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_160_168_specs_2	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_data_168_176_specs_3 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_168_176_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_168_176_3 = {
	"data-168-176",
	"data-168-176",
	&asn_OP_NativeInteger,
	asn_DEF_data_168_176_tags_3,
	sizeof(asn_DEF_data_168_176_tags_3)
		/sizeof(asn_DEF_data_168_176_tags_3[0]), /* 1 */
	asn_DEF_data_168_176_tags_3,	/* Same as above */
	sizeof(asn_DEF_data_168_176_tags_3)
		/sizeof(asn_DEF_data_168_176_tags_3[0]), /* 1 */
	{ &asn_OER_type_data_168_176_constr_3, &asn_PER_type_data_168_176_constr_3, data_168_176_3_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_168_176_specs_3	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_data_176_184_specs_4 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_176_184_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_176_184_4 = {
	"data-176-184",
	"data-176-184",
	&asn_OP_NativeInteger,
	asn_DEF_data_176_184_tags_4,
	sizeof(asn_DEF_data_176_184_tags_4)
		/sizeof(asn_DEF_data_176_184_tags_4[0]), /* 1 */
	asn_DEF_data_176_184_tags_4,	/* Same as above */
	sizeof(asn_DEF_data_176_184_tags_4)
		/sizeof(asn_DEF_data_176_184_tags_4[0]), /* 1 */
	{ &asn_OER_type_data_176_184_constr_4, &asn_PER_type_data_176_184_constr_4, data_176_184_4_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_176_184_specs_4	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_data_184_192_specs_5 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_184_192_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_184_192_5 = {
	"data-184-192",
	"data-184-192",
	&asn_OP_NativeInteger,
	asn_DEF_data_184_192_tags_5,
	sizeof(asn_DEF_data_184_192_tags_5)
		/sizeof(asn_DEF_data_184_192_tags_5[0]), /* 1 */
	asn_DEF_data_184_192_tags_5,	/* Same as above */
	sizeof(asn_DEF_data_184_192_tags_5)
		/sizeof(asn_DEF_data_184_192_tags_5[0]), /* 1 */
	{ &asn_OER_type_data_184_192_constr_5, &asn_PER_type_data_184_192_constr_5, data_184_192_5_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_184_192_specs_5	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_data_192_200_specs_6 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_192_200_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_192_200_6 = {
	"data-192-200",
	"data-192-200",
	&asn_OP_NativeInteger,
	asn_DEF_data_192_200_tags_6,
	sizeof(asn_DEF_data_192_200_tags_6)
		/sizeof(asn_DEF_data_192_200_tags_6[0]), /* 1 */
	asn_DEF_data_192_200_tags_6,	/* Same as above */
	sizeof(asn_DEF_data_192_200_tags_6)
		/sizeof(asn_DEF_data_192_200_tags_6[0]), /* 1 */
	{ &asn_OER_type_data_192_200_constr_6, &asn_PER_type_data_192_200_constr_6, data_192_200_6_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_192_200_specs_6	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_data_200_208_specs_7 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_200_208_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_200_208_7 = {
	"data-200-208",
	"data-200-208",
	&asn_OP_NativeInteger,
	asn_DEF_data_200_208_tags_7,
	sizeof(asn_DEF_data_200_208_tags_7)
		/sizeof(asn_DEF_data_200_208_tags_7[0]), /* 1 */
	asn_DEF_data_200_208_tags_7,	/* Same as above */
	sizeof(asn_DEF_data_200_208_tags_7)
		/sizeof(asn_DEF_data_200_208_tags_7[0]), /* 1 */
	{ &asn_OER_type_data_200_208_constr_7, &asn_PER_type_data_200_208_constr_7, data_200_208_7_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_200_208_specs_7	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_data_208_216_specs_8 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_208_216_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_208_216_8 = {
	"data-208-216",
	"data-208-216",
	&asn_OP_NativeInteger,
	asn_DEF_data_208_216_tags_8,
	sizeof(asn_DEF_data_208_216_tags_8)
		/sizeof(asn_DEF_data_208_216_tags_8[0]), /* 1 */
	asn_DEF_data_208_216_tags_8,	/* Same as above */
	sizeof(asn_DEF_data_208_216_tags_8)
		/sizeof(asn_DEF_data_208_216_tags_8[0]), /* 1 */
	{ &asn_OER_type_data_208_216_constr_8, &asn_PER_type_data_208_216_constr_8, data_208_216_8_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_208_216_specs_8	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_data_216_224_specs_9 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_216_224_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_216_224_9 = {
	"data-216-224",
	"data-216-224",
	&asn_OP_NativeInteger,
	asn_DEF_data_216_224_tags_9,
	sizeof(asn_DEF_data_216_224_tags_9)
		/sizeof(asn_DEF_data_216_224_tags_9[0]), /* 1 */
	asn_DEF_data_216_224_tags_9,	/* Same as above */
	sizeof(asn_DEF_data_216_224_tags_9)
		/sizeof(asn_DEF_data_216_224_tags_9[0]), /* 1 */
	{ &asn_OER_type_data_216_224_constr_9, &asn_PER_type_data_216_224_constr_9, data_216_224_9_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_216_224_specs_9	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_data_224_232_specs_10 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_224_232_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_224_232_10 = {
	"data-224-232",
	"data-224-232",
	&asn_OP_NativeInteger,
	asn_DEF_data_224_232_tags_10,
	sizeof(asn_DEF_data_224_232_tags_10)
		/sizeof(asn_DEF_data_224_232_tags_10[0]), /* 1 */
	asn_DEF_data_224_232_tags_10,	/* Same as above */
	sizeof(asn_DEF_data_224_232_tags_10)
		/sizeof(asn_DEF_data_224_232_tags_10[0]), /* 1 */
	{ &asn_OER_type_data_224_232_constr_10, &asn_PER_type_data_224_232_constr_10, data_224_232_10_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_224_232_specs_10	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_data_232_240_specs_11 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_232_240_tags_11[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_232_240_11 = {
	"data-232-240",
	"data-232-240",
	&asn_OP_NativeInteger,
	asn_DEF_data_232_240_tags_11,
	sizeof(asn_DEF_data_232_240_tags_11)
		/sizeof(asn_DEF_data_232_240_tags_11[0]), /* 1 */
	asn_DEF_data_232_240_tags_11,	/* Same as above */
	sizeof(asn_DEF_data_232_240_tags_11)
		/sizeof(asn_DEF_data_232_240_tags_11[0]), /* 1 */
	{ &asn_OER_type_data_232_240_constr_11, &asn_PER_type_data_232_240_constr_11, data_232_240_11_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_232_240_specs_11	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_data_240_specs_12 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_data_240_tags_12[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_240_12 = {
	"data-240",
	"data-240",
	&asn_OP_NativeInteger,
	asn_DEF_data_240_tags_12,
	sizeof(asn_DEF_data_240_tags_12)
		/sizeof(asn_DEF_data_240_tags_12[0]), /* 1 */
	asn_DEF_data_240_tags_12,	/* Same as above */
	sizeof(asn_DEF_data_240_tags_12)
		/sizeof(asn_DEF_data_240_tags_12[0]), /* 1 */
	{ &asn_OER_type_data_240_constr_12, &asn_PER_type_data_240_constr_12, data_240_12_constraint },
	0, 0,	/* No members */
	&asn_SPC_data_240_specs_12	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Pdcp_delay_pkt_count3_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count3, data_160_168),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_160_168_2,
		0,
		{ &asn_OER_memb_data_160_168_constr_2, &asn_PER_memb_data_160_168_constr_2,  memb_data_160_168_constraint_1 },
		0, 0, /* No default value */
		"data-160-168"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count3, data_168_176),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_168_176_3,
		0,
		{ &asn_OER_memb_data_168_176_constr_3, &asn_PER_memb_data_168_176_constr_3,  memb_data_168_176_constraint_1 },
		0, 0, /* No default value */
		"data-168-176"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count3, data_176_184),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_176_184_4,
		0,
		{ &asn_OER_memb_data_176_184_constr_4, &asn_PER_memb_data_176_184_constr_4,  memb_data_176_184_constraint_1 },
		0, 0, /* No default value */
		"data-176-184"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count3, data_184_192),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_184_192_5,
		0,
		{ &asn_OER_memb_data_184_192_constr_5, &asn_PER_memb_data_184_192_constr_5,  memb_data_184_192_constraint_1 },
		0, 0, /* No default value */
		"data-184-192"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count3, data_192_200),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_192_200_6,
		0,
		{ &asn_OER_memb_data_192_200_constr_6, &asn_PER_memb_data_192_200_constr_6,  memb_data_192_200_constraint_1 },
		0, 0, /* No default value */
		"data-192-200"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count3, data_200_208),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_200_208_7,
		0,
		{ &asn_OER_memb_data_200_208_constr_7, &asn_PER_memb_data_200_208_constr_7,  memb_data_200_208_constraint_1 },
		0, 0, /* No default value */
		"data-200-208"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count3, data_208_216),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_208_216_8,
		0,
		{ &asn_OER_memb_data_208_216_constr_8, &asn_PER_memb_data_208_216_constr_8,  memb_data_208_216_constraint_1 },
		0, 0, /* No default value */
		"data-208-216"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count3, data_216_224),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_216_224_9,
		0,
		{ &asn_OER_memb_data_216_224_constr_9, &asn_PER_memb_data_216_224_constr_9,  memb_data_216_224_constraint_1 },
		0, 0, /* No default value */
		"data-216-224"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count3, data_224_232),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_224_232_10,
		0,
		{ &asn_OER_memb_data_224_232_constr_10, &asn_PER_memb_data_224_232_constr_10,  memb_data_224_232_constraint_1 },
		0, 0, /* No default value */
		"data-224-232"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count3, data_232_240),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_232_240_11,
		0,
		{ &asn_OER_memb_data_232_240_constr_11, &asn_PER_memb_data_232_240_constr_11,  memb_data_232_240_constraint_1 },
		0, 0, /* No default value */
		"data-232-240"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Pdcp_delay_pkt_count3, data_240),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_data_240_12,
		0,
		{ &asn_OER_memb_data_240_constr_12, &asn_PER_memb_data_240_constr_12,  memb_data_240_constraint_1 },
		0, 0, /* No default value */
		"data-240"
		},
};
static const ber_tlv_tag_t asn_DEF_Pdcp_delay_pkt_count3_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Pdcp_delay_pkt_count3_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 10 }, /* data-160-168 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 9 }, /* data-168-176 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -2, 8 }, /* data-176-184 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, -3, 7 }, /* data-184-192 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, -4, 6 }, /* data-192-200 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 5, -5, 5 }, /* data-200-208 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 6, -6, 4 }, /* data-208-216 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 7, -7, 3 }, /* data-216-224 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 8, -8, 2 }, /* data-224-232 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 9, -9, 1 }, /* data-232-240 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 10, -10, 0 } /* data-240 */
};
asn_SEQUENCE_specifics_t asn_SPC_Pdcp_delay_pkt_count3_specs_1 = {
	sizeof(struct Pdcp_delay_pkt_count3),
	offsetof(struct Pdcp_delay_pkt_count3, _asn_ctx),
	asn_MAP_Pdcp_delay_pkt_count3_tag2el_1,
	11,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Pdcp_delay_pkt_count3 = {
	"Pdcp-delay-pkt-count3",
	"Pdcp-delay-pkt-count3",
	&asn_OP_SEQUENCE,
	asn_DEF_Pdcp_delay_pkt_count3_tags_1,
	sizeof(asn_DEF_Pdcp_delay_pkt_count3_tags_1)
		/sizeof(asn_DEF_Pdcp_delay_pkt_count3_tags_1[0]), /* 1 */
	asn_DEF_Pdcp_delay_pkt_count3_tags_1,	/* Same as above */
	sizeof(asn_DEF_Pdcp_delay_pkt_count3_tags_1)
		/sizeof(asn_DEF_Pdcp_delay_pkt_count3_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Pdcp_delay_pkt_count3_1,
	11,	/* Elements count */
	&asn_SPC_Pdcp_delay_pkt_count3_specs_1	/* Additional specs */
};

