/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_LTE_Contention_Resolution_Message_MSG4_Report_S_H;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_LL1_PCFICH_Decoding_Results_S_H;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_LL1_PCFICH_Decoding_Results_Record;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_LL1_RACH_Tx_Report_S_H;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_LL1_Serving_Cell_Measurement_Results_S_H;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_AdvRx_IC_Cell_List_S_H;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_AdvRx_IC_Cell_List_Neighbor;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_CA_Metrics_Log_Packet_S_H;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_CA_Metrics_Log_Packet_content;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_CA_Metrics_Log_Packet_scells;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Cell_Measurement_Results_S_H;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Cell_Measurement_Results_cell_measurement;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Common_DC_Offset_S_H;
extern struct asn_TYPE_descriptor_s asn_DEF_DCIReport;
extern struct asn_TYPE_descriptor_s asn_DEF_RecordHeader;
extern struct asn_TYPE_descriptor_s asn_DEF_DCIUL;
extern struct asn_TYPE_descriptor_s asn_DEF_DCIDL;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_GM_TX_Report_S_H;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_GM_TX_Report_R_H;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_GM_TX_Report_R_H_Exd;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_GM_TX_Report_R_H_PUCCH;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_GM_TX_Report_R_H_PUSCH;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Idle_Measurement_Request_S_H;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_1;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_2;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_6;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_cell;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_8;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_S_H;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_Payload_H;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_10;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_5;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer_cell;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Random_Access_Request_MSG1_Report_S_H;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Random_Access_Response_MSG2_Report_S_H;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_S_Criteria_Check_Procedure_S_H;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_S_Criteria_Check_Procedure_Subpacket_ID_4;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_S_Criteria_Check_Procedure_Subpacket_ID_9;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Serving_Cell_Information_S_H;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_ML1_Serving_Cell_Measurements_And_Evaluation_S_H;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_PDCP_DL_Data_PDU_Specific_Header;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_PDCP_DL_Data_PDU_Pdcp_State;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_PDCP_UL_Delay_Statistics_S_HEADER;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_PDCP_UL_Delay_Statistics_RBs;
extern struct asn_TYPE_descriptor_s asn_DEF_RLC_DL_AM_CONTROL_PDU_S_HEADER;
extern struct asn_TYPE_descriptor_s asn_DEF_RLC_DL_AM_CONTROL_PDU_PDU;
extern struct asn_TYPE_descriptor_s asn_DEF_RLC_DL_AM_Control_PDU_E1;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_RRC_Supported_CA_Combos_S_H;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_RRC_Supported_CA_Combos_CA_H;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_RRC_Supported_CA_Combos_Bw_Class;
extern struct asn_TYPE_descriptor_s asn_DEF_LTE_UE_Identification_Message_MSG3_Report_S_H;
extern struct asn_TYPE_descriptor_s asn_DEF_MetadataHeader;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module LTE-Contention-Resolution-Message-MSG4-Report in LTE_Contention_Resolution_Message_MSG4_Report.asn1 */
	&asn_DEF_LTE_Contention_Resolution_Message_MSG4_Report_S_H,	
	/* From module LTE-LL1-PCFICH-Decoding-Results in LTE_LL1_PCFICH_Decoding_Results.asn1 */
	&asn_DEF_LTE_LL1_PCFICH_Decoding_Results_S_H,	
	&asn_DEF_LTE_LL1_PCFICH_Decoding_Results_Record,	
	/* From module LTE-LL1-RACH-Tx-Report in LTE_LL1_RACH_TX_Report.asn1 */
	&asn_DEF_LTE_LL1_RACH_Tx_Report_S_H,	
	/* From module LTE-LL1-Serving-Cell-Measurement-Results in LTE_LL1_Serving_Cell_Measurement_Results.asn1 */
	&asn_DEF_LTE_LL1_Serving_Cell_Measurement_Results_S_H,	
	/* From module LTE-ML1-AdvRx-IC-Cell-List in LTE_ML1_AdvRx_IC_Cell_List.asn1 */
	&asn_DEF_LTE_ML1_AdvRx_IC_Cell_List_S_H,	
	&asn_DEF_LTE_ML1_AdvRx_IC_Cell_List_Neighbor,	
	/* From module LTE-ML1-CA-Metrics-Log-Packet in LTE_ML1_CA_Metrics_Log_Packet.asn1 */
	&asn_DEF_LTE_ML1_CA_Metrics_Log_Packet_S_H,	
	&asn_DEF_LTE_ML1_CA_Metrics_Log_Packet_content,	
	&asn_DEF_LTE_ML1_CA_Metrics_Log_Packet_scells,	
	/* From module LTE-ML1-Cell-Measurement-Results in LTE_ML1_Cell_Measurement_Results.asn1 */
	&asn_DEF_LTE_ML1_Cell_Measurement_Results_S_H,	
	&asn_DEF_LTE_ML1_Cell_Measurement_Results_cell_measurement,	
	/* From module LTE-ML1-Common-DC-Offset in LTE_ML1_Common _DC_Offset.asn1 */
	&asn_DEF_LTE_ML1_Common_DC_Offset_S_H,	
	/* From module DCIReportModule in LTE_ML1_DCI_Information_Report.asn1 */
	&asn_DEF_DCIReport,	
	&asn_DEF_RecordHeader,	
	&asn_DEF_DCIUL,	
	&asn_DEF_DCIDL,	
	/* From module LTE-ML1-GM-TX-Report in LTE_ML1_GM_TX_Report.asn1 */
	&asn_DEF_LTE_ML1_GM_TX_Report_S_H,	
	&asn_DEF_LTE_ML1_GM_TX_Report_R_H,	
	&asn_DEF_LTE_ML1_GM_TX_Report_R_H_Exd,	
	&asn_DEF_LTE_ML1_GM_TX_Report_R_H_PUCCH,	
	&asn_DEF_LTE_ML1_GM_TX_Report_R_H_PUSCH,	
	/* From module LTE-ML1-Idle-Measurement-Request in LTE_ML1_Idle_Measurement_Request.asn1 */
	&asn_DEF_LTE_ML1_Idle_Measurement_Request_S_H,	
	&asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_1,	
	&asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_2,	
	&asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_5,	
	&asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_6,	
	&asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7,	
	&asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_7_cell,	
	&asn_DEF_LTE_ML1_Idle_Measurement_Request_Sub_Pkt_8,	
	/* From module LTE-ML1-Intra-Frequency-Cell-Reselection in LTE_ML1_Intra_Frequency_Cell_Reselection.asn1 */
	&asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_S_H,	
	&asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_Payload_H,	
	&asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_10,	
	&asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_5,	
	&asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11,	
	&asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer,	
	&asn_DEF_LTE_ML1_Intra_Frequency_Cell_Reselection_pkt_11_layer_cell,	
	/* From module LTE-ML1-Random-Access-Request-MSG1-Report in LTE_ML1_Random_Access_Request_MSG1_ Report.asn1 */
	&asn_DEF_LTE_ML1_Random_Access_Request_MSG1_Report_S_H,	
	/* From module LTE-ML1-Random-Access-Response-MSG2-Report in LTE_ML1_Random_Access_Response_MSG2_Report.asn1 */
	&asn_DEF_LTE_ML1_Random_Access_Response_MSG2_Report_S_H,	
	/* From module LTE-ML1-S-Criteria-Check-Procedure in LTE_ML1_S_Criteria_Check_Procedure.asn1 */
	&asn_DEF_LTE_ML1_S_Criteria_Check_Procedure_S_H,	
	&asn_DEF_LTE_ML1_S_Criteria_Check_Procedure_Subpacket_ID_4,	
	&asn_DEF_LTE_ML1_S_Criteria_Check_Procedure_Subpacket_ID_9,	
	/* From module LTE-ML1-Serving-Cell-Information in LTE_ML1_Serving_Cell_Information.asn1 */
	&asn_DEF_LTE_ML1_Serving_Cell_Information_S_H,	
	/* From module LTE-ML1-Serving-Cell-Measurements-And-Evaluation in LTE_ML1_Serving_Cell_Measurements_And_Evaluation.asn1 */
	&asn_DEF_LTE_ML1_Serving_Cell_Measurements_And_Evaluation_S_H,	
	/* From module LTE-PDCP-DL-Data-PDU in LTE_PDCP_DL_Data_PDU.asn1 */
	&asn_DEF_LTE_PDCP_DL_Data_PDU_Specific_Header,	
	&asn_DEF_LTE_PDCP_DL_Data_PDU_Pdcp_State,	
	&asn_DEF_LTE_PDCP_DL_Data_PDU_Meta_Log_Buffer,	
	/* From module LTE-PDCP-UL-Delay-Statistics in LTE_PDCP_UL_Delay_Statistics.asn1 */
	&asn_DEF_LTE_PDCP_UL_Delay_Statistics_S_HEADER,	
	&asn_DEF_LTE_PDCP_UL_Delay_Statistics_RBs,	
	/* From module RLC-DL-AM-Control-PDU in LTE_RLC_DL_AM_Control_PDU.asn1 */
	&asn_DEF_RLC_DL_AM_CONTROL_PDU_S_HEADER,	
	&asn_DEF_RLC_DL_AM_CONTROL_PDU_PDU,	
	&asn_DEF_RLC_DL_AM_Control_PDU_E1,	
	/* From module LTE-RRC-Supported-CA-Combos in LTE_RRC_Supported_CA_Combos.asn1 */
	&asn_DEF_LTE_RRC_Supported_CA_Combos_S_H,	
	&asn_DEF_LTE_RRC_Supported_CA_Combos_CA_H,	
	&asn_DEF_LTE_RRC_Supported_CA_Combos_Bw_Class,	
	/* From module LTE-UE-Identification-Message-MSG3-Report in LTE_UE_Identification_Message_MSG3_Report.asn1 */
	&asn_DEF_LTE_UE_Identification_Message_MSG3_Report_S_H,	
	/* From module MetadataHeader in Metadata_Header.asn1 */
	&asn_DEF_MetadataHeader,	
	0
};

