/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Random-Access-Response-MSG2-Report"
 * 	found in "LTE_ML1_Random_Access_Response_MSG2_Report.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Rach_procedure_type_H_
#define	_Rach_procedure_type_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Rach_procedure_type {
	Rach_procedure_type_contention_Based	= 0,
	Rach_procedure_type_non_contention_based	= 1
} e_Rach_procedure_type;

/* Rach-procedure-type */
typedef long	 Rach_procedure_type_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Rach_procedure_type_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Rach_procedure_type;
extern const asn_INTEGER_specifics_t asn_SPC_Rach_procedure_type_specs_1;
asn_struct_free_f Rach_procedure_type_free;
asn_struct_print_f Rach_procedure_type_print;
asn_constr_check_f Rach_procedure_type_constraint;
ber_type_decoder_f Rach_procedure_type_decode_ber;
der_type_encoder_f Rach_procedure_type_encode_der;
xer_type_decoder_f Rach_procedure_type_decode_xer;
xer_type_encoder_f Rach_procedure_type_encode_xer;
oer_type_decoder_f Rach_procedure_type_decode_oer;
oer_type_encoder_f Rach_procedure_type_encode_oer;
per_type_decoder_f Rach_procedure_type_decode_uper;
per_type_encoder_f Rach_procedure_type_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Rach_procedure_type_H_ */
#include <asn_internal.h>
