/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Random-Access-Response-MSG2-Report"
 * 	found in "LTE_ML1_Random_Access_Response_MSG2_Report.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "RACH-Procedure-Mode.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_RACH_Procedure_Mode_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_RACH_Procedure_Mode_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  4 }	/* (0..4) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_RACH_Procedure_Mode_value2enum_1[] = {
	{ 0,	14,	"initial-Access" },
	{ 1,	8,	"unknown1" },
	{ 2,	8,	"unknown2" },
	{ 3,	8,	"unknown3" },
	{ 4,	8,	"unknown4" }
};
static const unsigned int asn_MAP_RACH_Procedure_Mode_enum2value_1[] = {
	0,	/* initial-Access(0) */
	1,	/* unknown1(1) */
	2,	/* unknown2(2) */
	3,	/* unknown3(3) */
	4	/* unknown4(4) */
};
const asn_INTEGER_specifics_t asn_SPC_RACH_Procedure_Mode_specs_1 = {
	asn_MAP_RACH_Procedure_Mode_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_RACH_Procedure_Mode_enum2value_1,	/* N => "tag"; sorted by N */
	5,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_RACH_Procedure_Mode_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_RACH_Procedure_Mode = {
	"RACH-Procedure-Mode",
	"RACH-Procedure-Mode",
	&asn_OP_NativeEnumerated,
	asn_DEF_RACH_Procedure_Mode_tags_1,
	sizeof(asn_DEF_RACH_Procedure_Mode_tags_1)
		/sizeof(asn_DEF_RACH_Procedure_Mode_tags_1[0]), /* 1 */
	asn_DEF_RACH_Procedure_Mode_tags_1,	/* Same as above */
	sizeof(asn_DEF_RACH_Procedure_Mode_tags_1)
		/sizeof(asn_DEF_RACH_Procedure_Mode_tags_1[0]), /* 1 */
	{ &asn_OER_type_RACH_Procedure_Mode_constr_1, &asn_PER_type_RACH_Procedure_Mode_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_RACH_Procedure_Mode_specs_1	/* Additional specs */
};

