/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Idle-Measurement-Request"
 * 	found in "LTE_ML1_Idle_Measurement_Request.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Rel_9_Info_H_
#define	_Rel_9_Info_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Rel-9-Info */
typedef struct Rel_9_Info {
	BIT_STRING_t	 skip5;
	long	 s_Non_Intra_Search_Q;
	BIT_STRING_t	 skip6;
	long	 thres_Serving_Low_Q;
	BIT_STRING_t	 skip8;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Rel_9_Info_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Rel_9_Info;
extern asn_SEQUENCE_specifics_t asn_SPC_Rel_9_Info_specs_1;
extern asn_TYPE_member_t asn_MBR_Rel_9_Info_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _Rel_9_Info_H_ */
#include <asn_internal.h>
