/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RLC-DL-AM-Control-PDU"
 * 	found in "LTE_RLC_DL_AM_Control_PDU.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "RLC-DL-AM-Control-PDU-E1.h"

static int
memb_nack_sn_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 511)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_e1_e1_exist_flag_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_e1_e2_exist_flag_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip9_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 5)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_nack_sn_constr_2 CC_NOTUSED = {
	{ 2, 1 }	/* (0..511) */,
	-1};
static asn_per_constraints_t asn_PER_memb_nack_sn_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 9,  9,  0,  511 }	/* (0..511) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_e1_e1_exist_flag_constr_3 CC_NOTUSED = {
	{ 1, 1 }	/* (0..1) */,
	-1};
static asn_per_constraints_t asn_PER_memb_e1_e1_exist_flag_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_e1_e2_exist_flag_constr_4 CC_NOTUSED = {
	{ 1, 1 }	/* (0..1) */,
	-1};
static asn_per_constraints_t asn_PER_memb_e1_e2_exist_flag_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip9_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	5	/* (SIZE(5..5)) */};
static asn_per_constraints_t asn_PER_memb_skip9_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  5,  5 }	/* (SIZE(5..5)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_RLC_DL_AM_Control_PDU_E1_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLC_DL_AM_Control_PDU_E1, nack_sn),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_nack_sn_constr_2, &asn_PER_memb_nack_sn_constr_2,  memb_nack_sn_constraint_1 },
		0, 0, /* No default value */
		"nack-sn"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLC_DL_AM_Control_PDU_E1, e1_e1_exist_flag),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_e1_e1_exist_flag_constr_3, &asn_PER_memb_e1_e1_exist_flag_constr_3,  memb_e1_e1_exist_flag_constraint_1 },
		0, 0, /* No default value */
		"e1-e1-exist-flag"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLC_DL_AM_Control_PDU_E1, e1_e2_exist_flag),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_e1_e2_exist_flag_constr_4, &asn_PER_memb_e1_e2_exist_flag_constr_4,  memb_e1_e2_exist_flag_constraint_1 },
		0, 0, /* No default value */
		"e1-e2-exist-flag"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLC_DL_AM_Control_PDU_E1, skip9),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip9_constr_5, &asn_PER_memb_skip9_constr_5,  memb_skip9_constraint_1 },
		0, 0, /* No default value */
		"skip9"
		},
};
static const ber_tlv_tag_t asn_DEF_RLC_DL_AM_Control_PDU_E1_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RLC_DL_AM_Control_PDU_E1_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 2 }, /* nack-sn */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 1 }, /* e1-e1-exist-flag */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -2, 0 }, /* e1-e2-exist-flag */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 3, 0, 0 } /* skip9 */
};
static asn_SEQUENCE_specifics_t asn_SPC_RLC_DL_AM_Control_PDU_E1_specs_1 = {
	sizeof(struct RLC_DL_AM_Control_PDU_E1),
	offsetof(struct RLC_DL_AM_Control_PDU_E1, _asn_ctx),
	asn_MAP_RLC_DL_AM_Control_PDU_E1_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RLC_DL_AM_Control_PDU_E1 = {
	"RLC-DL-AM-Control-PDU-E1",
	"RLC-DL-AM-Control-PDU-E1",
	&asn_OP_SEQUENCE,
	asn_DEF_RLC_DL_AM_Control_PDU_E1_tags_1,
	sizeof(asn_DEF_RLC_DL_AM_Control_PDU_E1_tags_1)
		/sizeof(asn_DEF_RLC_DL_AM_Control_PDU_E1_tags_1[0]), /* 1 */
	asn_DEF_RLC_DL_AM_Control_PDU_E1_tags_1,	/* Same as above */
	sizeof(asn_DEF_RLC_DL_AM_Control_PDU_E1_tags_1)
		/sizeof(asn_DEF_RLC_DL_AM_Control_PDU_E1_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RLC_DL_AM_Control_PDU_E1_1,
	4,	/* Elements count */
	&asn_SPC_RLC_DL_AM_Control_PDU_E1_specs_1	/* Additional specs */
};

