/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RLC-DL-AM-Control-PDU"
 * 	found in "LTE_RLC_DL_AM_Control_PDU.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "RLC-DL-AM-CONTROL-PDU-PDU.h"

static int
memb_skip5_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip6_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 4)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_sn_length_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_control_pdu_size_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_skip5_constr_3 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_skip5_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip6_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	4	/* (SIZE(4..4)) */};
static asn_per_constraints_t asn_PER_memb_skip6_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  4,  4 }	/* (SIZE(4..4)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_sn_length_constr_5 CC_NOTUSED = {
	{ 1, 1 }	/* (0..15) */,
	-1};
static asn_per_constraints_t asn_PER_memb_sn_length_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_control_pdu_size_constr_6 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_control_pdu_size_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_RLC_DL_AM_CONTROL_PDU_PDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLC_DL_AM_CONTROL_PDU_PDU, sys_time),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Sys_Time,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sys-time"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLC_DL_AM_CONTROL_PDU_PDU, skip5),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_skip5_constr_3, &asn_PER_memb_skip5_constr_3,  memb_skip5_constraint_1 },
		0, 0, /* No default value */
		"skip5"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLC_DL_AM_CONTROL_PDU_PDU, skip6),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip6_constr_4, &asn_PER_memb_skip6_constr_4,  memb_skip6_constraint_1 },
		0, 0, /* No default value */
		"skip6"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLC_DL_AM_CONTROL_PDU_PDU, sn_length),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_sn_length_constr_5, &asn_PER_memb_sn_length_constr_5,  memb_sn_length_constraint_1 },
		0, 0, /* No default value */
		"sn-length"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLC_DL_AM_CONTROL_PDU_PDU, control_pdu_size),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_control_pdu_size_constr_6, &asn_PER_memb_control_pdu_size_constr_6,  memb_control_pdu_size_constraint_1 },
		0, 0, /* No default value */
		"control-pdu-size"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLC_DL_AM_CONTROL_PDU_PDU, payload),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Payload,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"payload"
		},
};
static const ber_tlv_tag_t asn_DEF_RLC_DL_AM_CONTROL_PDU_PDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RLC_DL_AM_CONTROL_PDU_PDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 2 }, /* skip5 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, -1, 1 }, /* sn-length */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, -2, 0 }, /* control-pdu-size */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 2, 0, 0 }, /* skip6 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 1 }, /* sys-time */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -1, 0 } /* payload */
};
static asn_SEQUENCE_specifics_t asn_SPC_RLC_DL_AM_CONTROL_PDU_PDU_specs_1 = {
	sizeof(struct RLC_DL_AM_CONTROL_PDU_PDU),
	offsetof(struct RLC_DL_AM_CONTROL_PDU_PDU, _asn_ctx),
	asn_MAP_RLC_DL_AM_CONTROL_PDU_PDU_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RLC_DL_AM_CONTROL_PDU_PDU = {
	"RLC-DL-AM-CONTROL-PDU-PDU",
	"RLC-DL-AM-CONTROL-PDU-PDU",
	&asn_OP_SEQUENCE,
	asn_DEF_RLC_DL_AM_CONTROL_PDU_PDU_tags_1,
	sizeof(asn_DEF_RLC_DL_AM_CONTROL_PDU_PDU_tags_1)
		/sizeof(asn_DEF_RLC_DL_AM_CONTROL_PDU_PDU_tags_1[0]), /* 1 */
	asn_DEF_RLC_DL_AM_CONTROL_PDU_PDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_RLC_DL_AM_CONTROL_PDU_PDU_tags_1)
		/sizeof(asn_DEF_RLC_DL_AM_CONTROL_PDU_PDU_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RLC_DL_AM_CONTROL_PDU_PDU_1,
	6,	/* Elements count */
	&asn_SPC_RLC_DL_AM_CONTROL_PDU_PDU_specs_1	/* Additional specs */
};

