/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-PDCP-DL-Data-PDU"
 * 	found in "LTE_PDCP_DL_Data_PDU.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Rlcpath_H_
#define	_Rlcpath_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Rlcpath {
	Rlcpath_mcg	= 0,
	Rlcpath_unknown	= 1
} e_Rlcpath;

/* Rlcpath */
typedef long	 Rlcpath_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Rlcpath_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Rlcpath;
extern const asn_INTEGER_specifics_t asn_SPC_Rlcpath_specs_1;
asn_struct_free_f Rlcpath_free;
asn_struct_print_f Rlcpath_print;
asn_constr_check_f Rlcpath_constraint;
ber_type_decoder_f Rlcpath_decode_ber;
der_type_encoder_f Rlcpath_encode_der;
xer_type_decoder_f Rlcpath_decode_xer;
xer_type_encoder_f Rlcpath_encode_xer;
oer_type_decoder_f Rlcpath_decode_oer;
oer_type_encoder_f Rlcpath_encode_oer;
per_type_decoder_f Rlcpath_decode_uper;
per_type_encoder_f Rlcpath_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Rlcpath_H_ */
#include <asn_internal.h>
