/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-GM-TX-Report"
 * 	found in "LTE_ML1_GM_TX_Report.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Scheduling_request_present_H_
#define	_Scheduling_request_present_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Scheduling_request_present {
	Scheduling_request_present_not_present	= 0,
	Scheduling_request_present_present	= 1
} e_Scheduling_request_present;

/* Scheduling-request-present */
typedef long	 Scheduling_request_present_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Scheduling_request_present_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Scheduling_request_present;
extern const asn_INTEGER_specifics_t asn_SPC_Scheduling_request_present_specs_1;
asn_struct_free_f Scheduling_request_present_free;
asn_struct_print_f Scheduling_request_present_print;
asn_constr_check_f Scheduling_request_present_constraint;
ber_type_decoder_f Scheduling_request_present_decode_ber;
der_type_encoder_f Scheduling_request_present_encode_der;
xer_type_decoder_f Scheduling_request_present_decode_xer;
xer_type_encoder_f Scheduling_request_present_encode_xer;
oer_type_decoder_f Scheduling_request_present_decode_oer;
oer_type_encoder_f Scheduling_request_present_encode_oer;
per_type_decoder_f Scheduling_request_present_decode_uper;
per_type_encoder_f Scheduling_request_present_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Scheduling_request_present_H_ */
#include <asn_internal.h>
