/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-AdvRx-IC-Cell-List"
 * 	found in "LTE_ML1_AdvRx_IC_Cell_List.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Serving_H_
#define	_Serving_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <BIT_STRING.h>
#include "Cell-type.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Serving */
typedef struct Serving {
	long	 serving_cell_id;
	long	 dl_Bandwidth;
	long	 num_Antennas;
	OCTET_STRING_t	 skip6;
	long	 filt_rsrp_data;
	OCTET_STRING_t	 skip14;
	BIT_STRING_t	 skip7;
	Cell_type_t	 cell_type;
	long	 iC_Inr_Use_Nb;
	long	 rsrp_use_nb;
	OCTET_STRING_t	 skip8;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Serving_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Serving;
extern asn_SEQUENCE_specifics_t asn_SPC_Serving_specs_1;
extern asn_TYPE_member_t asn_MBR_Serving_1[11];

#ifdef __cplusplus
}
#endif

#endif	/* _Serving_H_ */
#include <asn_internal.h>
