/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Idle-Measurement-Request"
 * 	found in "LTE_ML1_Idle_Measurement_Request.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "SubPacket-Idle-Meas-Serving-Frequency-Resel-Info.h"

static int
memb_versions_Standards_Version_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip3_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 16)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_serving_Cell_Priority_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_s_Non_Intra_Search_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_thresh_Serving_Low_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_skip4_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 20)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_versions_Standards_Version_constr_2 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65535) */,
	-1};
static asn_per_constraints_t asn_PER_memb_versions_Standards_Version_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip3_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	16	/* (SIZE(16..16)) */};
static asn_per_constraints_t asn_PER_memb_skip3_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  16,  16 }	/* (SIZE(16..16)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_serving_Cell_Priority_constr_4 CC_NOTUSED = {
	{ 1, 1 }	/* (0..15) */,
	-1};
static asn_per_constraints_t asn_PER_memb_serving_Cell_Priority_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_s_Non_Intra_Search_constr_5 CC_NOTUSED = {
	{ 1, 1 }	/* (0..15) */,
	-1};
static asn_per_constraints_t asn_PER_memb_s_Non_Intra_Search_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_thresh_Serving_Low_constr_6 CC_NOTUSED = {
	{ 1, 1 }	/* (0..15) */,
	-1};
static asn_per_constraints_t asn_PER_memb_thresh_Serving_Low_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_skip4_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	20	/* (SIZE(20..20)) */};
static asn_per_constraints_t asn_PER_memb_skip4_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  20,  20 }	/* (SIZE(20..20)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_SubPacket_Idle_Meas_Serving_Frequency_Resel_Info_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SubPacket_Idle_Meas_Serving_Frequency_Resel_Info, versions_Standards_Version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_versions_Standards_Version_constr_2, &asn_PER_memb_versions_Standards_Version_constr_2,  memb_versions_Standards_Version_constraint_1 },
		0, 0, /* No default value */
		"versions-Standards-Version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubPacket_Idle_Meas_Serving_Frequency_Resel_Info, skip3),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip3_constr_3, &asn_PER_memb_skip3_constr_3,  memb_skip3_constraint_1 },
		0, 0, /* No default value */
		"skip3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubPacket_Idle_Meas_Serving_Frequency_Resel_Info, serving_Cell_Priority),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_serving_Cell_Priority_constr_4, &asn_PER_memb_serving_Cell_Priority_constr_4,  memb_serving_Cell_Priority_constraint_1 },
		0, 0, /* No default value */
		"serving-Cell-Priority"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubPacket_Idle_Meas_Serving_Frequency_Resel_Info, s_Non_Intra_Search),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_s_Non_Intra_Search_constr_5, &asn_PER_memb_s_Non_Intra_Search_constr_5,  memb_s_Non_Intra_Search_constraint_1 },
		0, 0, /* No default value */
		"s-Non-Intra-Search"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubPacket_Idle_Meas_Serving_Frequency_Resel_Info, thresh_Serving_Low),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_thresh_Serving_Low_constr_6, &asn_PER_memb_thresh_Serving_Low_constr_6,  memb_thresh_Serving_Low_constraint_1 },
		0, 0, /* No default value */
		"thresh-Serving-Low"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubPacket_Idle_Meas_Serving_Frequency_Resel_Info, skip4),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip4_constr_7, &asn_PER_memb_skip4_constr_7,  memb_skip4_constraint_1 },
		0, 0, /* No default value */
		"skip4"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubPacket_Idle_Meas_Serving_Frequency_Resel_Info, rel_9_Info),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Rel_9_Info,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rel-9-Info"
		},
};
static const ber_tlv_tag_t asn_DEF_SubPacket_Idle_Meas_Serving_Frequency_Resel_Info_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SubPacket_Idle_Meas_Serving_Frequency_Resel_Info_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 3 }, /* versions-Standards-Version */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -1, 2 }, /* serving-Cell-Priority */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, -2, 1 }, /* s-Non-Intra-Search */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, -3, 0 }, /* thresh-Serving-Low */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 1, 0, 1 }, /* skip3 */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 5, -1, 0 }, /* skip4 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 6, 0, 0 } /* rel-9-Info */
};
asn_SEQUENCE_specifics_t asn_SPC_SubPacket_Idle_Meas_Serving_Frequency_Resel_Info_specs_1 = {
	sizeof(struct SubPacket_Idle_Meas_Serving_Frequency_Resel_Info),
	offsetof(struct SubPacket_Idle_Meas_Serving_Frequency_Resel_Info, _asn_ctx),
	asn_MAP_SubPacket_Idle_Meas_Serving_Frequency_Resel_Info_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SubPacket_Idle_Meas_Serving_Frequency_Resel_Info = {
	"SubPacket-Idle-Meas-Serving-Frequency-Resel-Info",
	"SubPacket-Idle-Meas-Serving-Frequency-Resel-Info",
	&asn_OP_SEQUENCE,
	asn_DEF_SubPacket_Idle_Meas_Serving_Frequency_Resel_Info_tags_1,
	sizeof(asn_DEF_SubPacket_Idle_Meas_Serving_Frequency_Resel_Info_tags_1)
		/sizeof(asn_DEF_SubPacket_Idle_Meas_Serving_Frequency_Resel_Info_tags_1[0]), /* 1 */
	asn_DEF_SubPacket_Idle_Meas_Serving_Frequency_Resel_Info_tags_1,	/* Same as above */
	sizeof(asn_DEF_SubPacket_Idle_Meas_Serving_Frequency_Resel_Info_tags_1)
		/sizeof(asn_DEF_SubPacket_Idle_Meas_Serving_Frequency_Resel_Info_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SubPacket_Idle_Meas_Serving_Frequency_Resel_Info_1,
	7,	/* Elements count */
	&asn_SPC_SubPacket_Idle_Meas_Serving_Frequency_Resel_Info_specs_1	/* Additional specs */
};

