/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Idle-Measurement-Request"
 * 	found in "LTE_ML1_Idle_Measurement_Request.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info_H_
#define	_SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SubPacket-Idle-Meas-Intra-Frequency-Whitelist-Info */
typedef struct SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info {
	BIT_STRING_t	 skip15;
	long	 versions_Num_White_Listed_Cells;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info;
extern asn_SEQUENCE_specifics_t asn_SPC_SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info_specs_1;
extern asn_TYPE_member_t asn_MBR_SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info_H_ */
#include <asn_internal.h>
