/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Idle-Measurement-Request"
 * 	found in "LTE_ML1_Idle_Measurement_Request.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "SubPacket-Idle-Meas-Common-Config.h"

static int
memb_versions_Idle_Meas_Removal_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_idle_Meas_Included_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_versions_Idle_Meas_Removal_constr_2 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65535) */,
	-1};
static asn_per_constraints_t asn_PER_memb_versions_Idle_Meas_Removal_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_idle_Meas_Included_constr_3 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65535) */,
	-1};
static asn_per_constraints_t asn_PER_memb_idle_Meas_Included_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_SubPacket_Idle_Meas_Common_Config_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SubPacket_Idle_Meas_Common_Config, versions_Idle_Meas_Removal),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_versions_Idle_Meas_Removal_constr_2, &asn_PER_memb_versions_Idle_Meas_Removal_constr_2,  memb_versions_Idle_Meas_Removal_constraint_1 },
		0, 0, /* No default value */
		"versions-Idle-Meas-Removal"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubPacket_Idle_Meas_Common_Config, idle_Meas_Included),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_idle_Meas_Included_constr_3, &asn_PER_memb_idle_Meas_Included_constr_3,  memb_idle_Meas_Included_constraint_1 },
		0, 0, /* No default value */
		"idle-Meas-Included"
		},
};
static const ber_tlv_tag_t asn_DEF_SubPacket_Idle_Meas_Common_Config_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SubPacket_Idle_Meas_Common_Config_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* versions-Idle-Meas-Removal */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 } /* idle-Meas-Included */
};
asn_SEQUENCE_specifics_t asn_SPC_SubPacket_Idle_Meas_Common_Config_specs_1 = {
	sizeof(struct SubPacket_Idle_Meas_Common_Config),
	offsetof(struct SubPacket_Idle_Meas_Common_Config, _asn_ctx),
	asn_MAP_SubPacket_Idle_Meas_Common_Config_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SubPacket_Idle_Meas_Common_Config = {
	"SubPacket-Idle-Meas-Common-Config",
	"SubPacket-Idle-Meas-Common-Config",
	&asn_OP_SEQUENCE,
	asn_DEF_SubPacket_Idle_Meas_Common_Config_tags_1,
	sizeof(asn_DEF_SubPacket_Idle_Meas_Common_Config_tags_1)
		/sizeof(asn_DEF_SubPacket_Idle_Meas_Common_Config_tags_1[0]), /* 1 */
	asn_DEF_SubPacket_Idle_Meas_Common_Config_tags_1,	/* Same as above */
	sizeof(asn_DEF_SubPacket_Idle_Meas_Common_Config_tags_1)
		/sizeof(asn_DEF_SubPacket_Idle_Meas_Common_Config_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SubPacket_Idle_Meas_Common_Config_1,
	2,	/* Elements count */
	&asn_SPC_SubPacket_Idle_Meas_Common_Config_specs_1	/* Additional specs */
};

