/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Idle-Measurement-Request"
 * 	found in "LTE_ML1_Idle_Measurement_Request.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "SubPacket-Idle-Meas-Intra-Frequency-Whitelist-Info.h"

static int
memb_skip15_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 13)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_versions_Num_White_Listed_Cells_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 7)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_skip15_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	13	/* (SIZE(13..13)) */};
static asn_per_constraints_t asn_PER_memb_skip15_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  13,  13 }	/* (SIZE(13..13)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_versions_Num_White_Listed_Cells_constr_3 CC_NOTUSED = {
	{ 1, 1 }	/* (0..7) */,
	-1};
static asn_per_constraints_t asn_PER_memb_versions_Num_White_Listed_Cells_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info, skip15),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_skip15_constr_2, &asn_PER_memb_skip15_constr_2,  memb_skip15_constraint_1 },
		0, 0, /* No default value */
		"skip15"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info, versions_Num_White_Listed_Cells),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_versions_Num_White_Listed_Cells_constr_3, &asn_PER_memb_versions_Num_White_Listed_Cells_constr_3,  memb_versions_Num_White_Listed_Cells_constraint_1 },
		0, 0, /* No default value */
		"versions-Num-White-Listed-Cells"
		},
};
static const ber_tlv_tag_t asn_DEF_SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* versions-Num-White-Listed-Cells */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 0, 0, 0 } /* skip15 */
};
asn_SEQUENCE_specifics_t asn_SPC_SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info_specs_1 = {
	sizeof(struct SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info),
	offsetof(struct SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info, _asn_ctx),
	asn_MAP_SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info = {
	"SubPacket-Idle-Meas-Intra-Frequency-Whitelist-Info",
	"SubPacket-Idle-Meas-Intra-Frequency-Whitelist-Info",
	&asn_OP_SEQUENCE,
	asn_DEF_SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info_tags_1,
	sizeof(asn_DEF_SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info_tags_1)
		/sizeof(asn_DEF_SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info_tags_1[0]), /* 1 */
	asn_DEF_SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info_tags_1,	/* Same as above */
	sizeof(asn_DEF_SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info_tags_1)
		/sizeof(asn_DEF_SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info_1,
	2,	/* Elements count */
	&asn_SPC_SubPacket_Idle_Meas_Intra_Frequency_Whitelist_Info_specs_1	/* Additional specs */
};

