/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Idle-Measurement-Request"
 * 	found in "LTE_ML1_Idle_Measurement_Request.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_SubPacket_Idle_Meas_Intra_Frequency_Common_Config_Resel_Info_H_
#define	_SubPacket_Idle_Meas_Intra_Frequency_Common_Config_Resel_Info_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include <OCTET_STRING.h>
#include "Rel-9-Info-subpkt-6.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SubPacket-Idle-Meas-Intra-Frequency-Common-Config-Resel-Info */
typedef struct SubPacket_Idle_Meas_Intra_Frequency_Common_Config_Resel_Info {
	long	 versions_Standards_Version;
	BIT_STRING_t	 skip10;
	long	 qrxlevmin_for_Intra_Freq_Neighbors_Data;
	long	 p_max_Data;
	long	 treselection_EUTRAN;
	long	 measurement_BW;
	long	 cSG_PCI_Range_Present;
	long	 neighbor_Cell_Config;
	long	 treselection_EUTRAN_High;
	long	 treselection_EUTRAN_Medium;
	long	 cSG_PCI_Range_Start_PCI;
	long	 cSG_PCI_Range_End_PCI;
	long	 s_Intra_Search_Raw;
	OCTET_STRING_t	 skip11;
	Rel_9_Info_subpkt_6_t	 rel_9_Info_subpkt_6;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SubPacket_Idle_Meas_Intra_Frequency_Common_Config_Resel_Info_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SubPacket_Idle_Meas_Intra_Frequency_Common_Config_Resel_Info;
extern asn_SEQUENCE_specifics_t asn_SPC_SubPacket_Idle_Meas_Intra_Frequency_Common_Config_Resel_Info_specs_1;
extern asn_TYPE_member_t asn_MBR_SubPacket_Idle_Meas_Intra_Frequency_Common_Config_Resel_Info_1[15];

#ifdef __cplusplus
}
#endif

#endif	/* _SubPacket_Idle_Meas_Intra_Frequency_Common_Config_Resel_Info_H_ */
#include <asn_internal.h>
