/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-CA-Metrics-Log-Packet"
 * 	found in "LTE_ML1_CA_Metrics_Log_Packet.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "Total-metrics.h"

asn_TYPE_member_t asn_MBR_Total_metrics_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Total_metrics, pcell_only),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Pcell_only,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pcell-only"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Total_metrics, scell_only),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Pcell_only,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"scell-only"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Total_metrics, pcell_and_scell_any),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Pcell_only,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pcell-and-scell-any"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Total_metrics, pcell),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Pcell_only,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pcell"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Total_metrics, structure_end),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Structure_end,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"structure-end"
		},
};
static const ber_tlv_tag_t asn_DEF_Total_metrics_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Total_metrics_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 4 }, /* pcell-only */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 3 }, /* scell-only */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -2, 2 }, /* pcell-and-scell-any */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -3, 1 }, /* pcell */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -4, 0 } /* structure-end */
};
asn_SEQUENCE_specifics_t asn_SPC_Total_metrics_specs_1 = {
	sizeof(struct Total_metrics),
	offsetof(struct Total_metrics, _asn_ctx),
	asn_MAP_Total_metrics_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Total_metrics = {
	"Total-metrics",
	"Total-metrics",
	&asn_OP_SEQUENCE,
	asn_DEF_Total_metrics_tags_1,
	sizeof(asn_DEF_Total_metrics_tags_1)
		/sizeof(asn_DEF_Total_metrics_tags_1[0]), /* 1 */
	asn_DEF_Total_metrics_tags_1,	/* Same as above */
	sizeof(asn_DEF_Total_metrics_tags_1)
		/sizeof(asn_DEF_Total_metrics_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Total_metrics_1,
	5,	/* Elements count */
	&asn_SPC_Total_metrics_specs_1	/* Additional specs */
};

