/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-PDCP-UL-Delay-Statistics"
 * 	found in "LTE_PDCP_UL_Delay_Statistics.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Total_H_
#define	_Total_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Pdcp-delay-pkt-count.h"
#include "Pdcp-delay-pkt-count2.h"
#include "Pdcp-delay-pkt-count3.h"
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Total */
typedef struct Total {
	Pdcp_delay_pkt_count_t	 pdcp_delay_pkt_count;
	Pdcp_delay_pkt_count2_t	 pdcp_delay_pkt_count2;
	Pdcp_delay_pkt_count3_t	 pdcp_delay_pkt_count3;
	long	 num_discard_pdu;
	long	 discard_pdu_bytes;
	OCTET_STRING_t	 skip3;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Total_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Total;
extern asn_SEQUENCE_specifics_t asn_SPC_Total_specs_1;
extern asn_TYPE_member_t asn_MBR_Total_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _Total_H_ */
#include <asn_internal.h>
