/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-GM-TX-Report"
 * 	found in "LTE_ML1_GM_TX_Report.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Tti_bundle_index_H_
#define	_Tti_bundle_index_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Tti_bundle_index {
	Tti_bundle_index_invalid	= 0,
	Tti_bundle_index_valid	= 1
} e_Tti_bundle_index;

/* Tti-bundle-index */
typedef long	 Tti_bundle_index_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Tti_bundle_index_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Tti_bundle_index;
extern const asn_INTEGER_specifics_t asn_SPC_Tti_bundle_index_specs_1;
asn_struct_free_f Tti_bundle_index_free;
asn_struct_print_f Tti_bundle_index_print;
asn_constr_check_f Tti_bundle_index_constraint;
ber_type_decoder_f Tti_bundle_index_decode_ber;
der_type_encoder_f Tti_bundle_index_encode_der;
xer_type_decoder_f Tti_bundle_index_decode_xer;
xer_type_encoder_f Tti_bundle_index_encode_xer;
oer_type_decoder_f Tti_bundle_index_decode_oer;
oer_type_encoder_f Tti_bundle_index_encode_oer;
per_type_decoder_f Tti_bundle_index_decode_uper;
per_type_encoder_f Tti_bundle_index_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Tti_bundle_index_H_ */
#include <asn_internal.h>
