/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-RRC-Supported-CA-Combos"
 * 	found in "LTE_RRC_Supported_CA_Combos.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#include "Ul-Max-Antennas-Index.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_Ul_Max_Antennas_Index_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_Ul_Max_Antennas_Index_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  4 }	/* (0..4) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_Ul_Max_Antennas_Index_value2enum_1[] = {
	{ 0,	19,	"cLASS-INVALID-INDEX" },
	{ 1,	13,	"cLASS-A-1-ANT" },
	{ 2,	13,	"cLASS-A-2-ANT" },
	{ 3,	13,	"cLASS-A-4-ANT" },
	{ 4,	16,	"cLASS-BC-1-1-ANT" }
};
static const unsigned int asn_MAP_Ul_Max_Antennas_Index_enum2value_1[] = {
	1,	/* cLASS-A-1-ANT(1) */
	2,	/* cLASS-A-2-ANT(2) */
	3,	/* cLASS-A-4-ANT(3) */
	4,	/* cLASS-BC-1-1-ANT(4) */
	0	/* cLASS-INVALID-INDEX(0) */
};
const asn_INTEGER_specifics_t asn_SPC_Ul_Max_Antennas_Index_specs_1 = {
	asn_MAP_Ul_Max_Antennas_Index_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_Ul_Max_Antennas_Index_enum2value_1,	/* N => "tag"; sorted by N */
	5,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_Ul_Max_Antennas_Index_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Ul_Max_Antennas_Index = {
	"Ul-Max-Antennas-Index",
	"Ul-Max-Antennas-Index",
	&asn_OP_NativeEnumerated,
	asn_DEF_Ul_Max_Antennas_Index_tags_1,
	sizeof(asn_DEF_Ul_Max_Antennas_Index_tags_1)
		/sizeof(asn_DEF_Ul_Max_Antennas_Index_tags_1[0]), /* 1 */
	asn_DEF_Ul_Max_Antennas_Index_tags_1,	/* Same as above */
	sizeof(asn_DEF_Ul_Max_Antennas_Index_tags_1)
		/sizeof(asn_DEF_Ul_Max_Antennas_Index_tags_1[0]), /* 1 */
	{ &asn_OER_type_Ul_Max_Antennas_Index_constr_1, &asn_PER_type_Ul_Max_Antennas_Index_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_Ul_Max_Antennas_Index_specs_1	/* Additional specs */
};

