/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-CA-Metrics-Log-Packet"
 * 	found in "LTE_ML1_CA_Metrics_Log_Packet.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Ul_state_H_
#define	_Ul_state_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ul_state {
	Ul_state_not_configured	= 0,
	Ul_state_configfured	= 1
} e_Ul_state;

/* Ul-state */
typedef long	 Ul_state_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ul_state_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ul_state;
extern const asn_INTEGER_specifics_t asn_SPC_Ul_state_specs_1;
asn_struct_free_f Ul_state_free;
asn_struct_print_f Ul_state_print;
asn_constr_check_f Ul_state_constraint;
ber_type_decoder_f Ul_state_decode_ber;
der_type_encoder_f Ul_state_encode_der;
xer_type_decoder_f Ul_state_decode_xer;
xer_type_encoder_f Ul_state_encode_xer;
oer_type_decoder_f Ul_state_decode_oer;
oer_type_encoder_f Ul_state_encode_oer;
per_type_decoder_f Ul_state_decode_uper;
per_type_encoder_f Ul_state_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ul_state_H_ */
#include <asn_internal.h>
