/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-Common-DC-Offset"
 * 	found in "LTE_ML1_Common _DC_Offset.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Update_H_
#define	_Update_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Update {
	Update_table_was_retrieved	= 0,
	Update_table_was_updated	= 1
} e_Update;

/* Update */
typedef long	 Update_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Update_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Update;
extern const asn_INTEGER_specifics_t asn_SPC_Update_specs_1;
asn_struct_free_f Update_free;
asn_struct_print_f Update_print;
asn_constr_check_f Update_constraint;
ber_type_decoder_f Update_decode_ber;
der_type_encoder_f Update_encode_der;
xer_type_decoder_f Update_decode_xer;
xer_type_encoder_f Update_encode_xer;
oer_type_decoder_f Update_decode_oer;
oer_type_encoder_f Update_encode_oer;
per_type_decoder_f Update_decode_uper;
per_type_encoder_f Update_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Update_H_ */
#include <asn_internal.h>
