/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTE-ML1-S-Criteria-Check-Procedure"
 * 	found in "LTE_ML1_S_Criteria_Check_Procedure.asn1"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER -pdu=auto`
 */

#ifndef	_Versions_Standards_Version_H_
#define	_Versions_Standards_Version_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Versions_Standards_Version {
	Versions_Standards_Version_unknown0	= 0,
	Versions_Standards_Version_release_9	= 1,
	Versions_Standards_Version_unknown2	= 2
} e_Versions_Standards_Version;

/* Versions-Standards-Version */
typedef long	 Versions_Standards_Version_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Versions_Standards_Version_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Versions_Standards_Version;
extern const asn_INTEGER_specifics_t asn_SPC_Versions_Standards_Version_specs_1;
asn_struct_free_f Versions_Standards_Version_free;
asn_struct_print_f Versions_Standards_Version_print;
asn_constr_check_f Versions_Standards_Version_constraint;
ber_type_decoder_f Versions_Standards_Version_decode_ber;
der_type_encoder_f Versions_Standards_Version_encode_der;
xer_type_decoder_f Versions_Standards_Version_decode_xer;
xer_type_encoder_f Versions_Standards_Version_encode_xer;
oer_type_decoder_f Versions_Standards_Version_decode_oer;
oer_type_encoder_f Versions_Standards_Version_encode_oer;
per_type_decoder_f Versions_Standards_Version_decode_uper;
per_type_encoder_f Versions_Standards_Version_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Versions_Standards_Version_H_ */
#include <asn_internal.h>
